# Generated by Django 2.2.1 on 2019-06-01 15:31

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('campaign', '0001_initial'), ('campaign', '0002_remove_event_pilot'), ('campaign', '0003_auto_20190512_1626'), ('campaign', '0004_auto_20190512_1640'), ('campaign', '0005_achievement_threat'), ('campaign', '0006_auto_20190513_2235'), ('campaign', '0007_auto_20190513_2244'), ('campaign', '0008_auto_20190514_0235'), ('campaign', '0009_session_outcome'), ('campaign', '0010_ship_slot_upgrade'), ('campaign', '0011_auto_20190517_2348'), ('campaign', '0012_auto_20190517_2350'), ('campaign', '0013_auto_20190520_2155')]

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('victory', models.PositiveSmallIntegerField(default=1)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('story', models.CharField(max_length=30)),
                ('territory', models.CharField(choices=[('F', 'Friendly'), ('N', 'Neutral'), ('H', 'Hostile')], max_length=1)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=30)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Mission')),
                ('pilots', models.ManyToManyField(to='campaign.Pilot')),
                ('date', models.DateField(default=datetime.date(2019, 6, 1))),
                ('outcome', models.CharField(choices=[('V', 'Victory'), ('F', 'Failure'), ('U', 'Unresolved')], default='U', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(max_length=25)),
                ('long_desc', models.CharField(max_length=60)),
                ('xp', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.Event')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Pilot')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Session')),
                ('turn', models.PositiveSmallIntegerField(default=1)),
                ('threat', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat', models.PositiveSmallIntegerField()),
                ('cost', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Configuration'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('GNR', 'Gunner'), ('ILC', 'Illicit'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TLN', 'Talent'), ('TCH', 'Tech'), ('TTL', 'Title'), ('TRP', 'Torpedo'), ('TRT', 'Turret'), ('SHP', 'Ship'), ('PLT', 'Pilot'), ('THR', 'Initiative'), ('FCH', 'Force Charge'), ('CHR', 'Charge'), ('WLD', 'Wildcard')], max_length=3)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Slot')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Ship')),
            ],
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Configuration'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('GNR', 'Gunner'), ('ILC', 'Illicit'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TLN', 'Talent'), ('TCH', 'Tech'), ('TTL', 'Title'), ('TRP', 'Torpedo'), ('TRT', 'Turret'), ('SHP', 'Ship'), ('PLT', 'Pilot'), ('THR', 'Initiative'), ('FCH', 'Force Charge'), ('CHR', 'Charge'), ('WLD', 'Wildcard')], max_length=3)),
                ('type2', models.CharField(blank=True, choices=[('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Configuration'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('GNR', 'Gunner'), ('ILC', 'Illicit'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TLN', 'Talent'), ('TCH', 'Tech'), ('TTL', 'Title'), ('TRP', 'Torpedo'), ('TRT', 'Turret'), ('SHP', 'Ship'), ('PLT', 'Pilot'), ('THR', 'Initiative'), ('FCH', 'Force Charge'), ('CHR', 'Charge'), ('WLD', 'Wildcard')], default=None, max_length=3, null=True)),
                ('cost', models.PositiveSmallIntegerField()),
                ('ability', models.CharField(max_length=75)),
                ('charges', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PilotShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Pilot')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Ship')),
                ('unlocked', models.ManyToManyField(to='campaign.Slot')),
            ],
        ),
    ]
