# Generated by Django 3.2 on 2022-07-03 20:39

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xwtools', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flee', models.PositiveSmallIntegerField(default=0)),
                ('dial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwtools.dial')),
            ],
            options={
                'verbose_name_plural': 'AI',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('victory', models.PositiveSmallIntegerField(default=12)),
                ('pool_xp', models.BooleanField(default=False)),
                ('deck_draw', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnemyAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, 'Basic'), (2, 'Elite'), (3, 'In 3'), (4, 'In 4'), (5, 'In 5')], default=1)),
                ('card', models.ForeignKey(limit_choices_to={'ai_description__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='xwtools.card')),
            ],
        ),
        migrations.CreateModel(
            name='EnemyPilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_override', models.CharField(blank=True, max_length=35, null=True)),
                ('random', models.BooleanField(default=True)),
                ('chassis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwtools.chassis')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwtools.faction')),
                ('upgrades', models.ManyToManyField(through='campaign.EnemyAbility', to='xwtools.Card')),
            ],
        ),
        migrations.CreateModel(
            name='FlightGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('arrival', models.SmallIntegerField(default=1)),
                ('vector', models.CharField(max_length=6)),
                ('orders', models.CharField(choices=[('A', 'Attack'), ('S', 'Strike'), ('E', 'Escort'), ('X', 'Special')], default='A', max_length=1)),
            ],
            options={
                'verbose_name': 'Flight Group',
                'verbose_name_plural': 'Flight Groups',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('story', models.CharField(max_length=30)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('territory', models.CharField(choices=[('F', 'Friendly'), ('N', 'Neutral'), ('H', 'Hostile')], default='N', max_length=1)),
                ('turns', models.PositiveSmallIntegerField(default=12)),
                ('player_vp', models.BooleanField(default=False)),
                ('enemy_vp', models.BooleanField(default=False)),
                ('objective', models.TextField()),
                ('bonus_1', models.TextField(blank=True, null=True)),
                ('bonus_2', models.TextField(blank=True, null=True)),
                ('penalty', models.TextField(blank=True, null=True)),
                ('ground_assault', models.BooleanField(default=False)),
                ('enemy_faction', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xwtools.faction')),
            ],
            options={
                'ordering': ['story', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='MissionFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('E', 'Emplacement'), ('O', 'Obstacle'), ('T', 'Terrain')], max_length=1)),
                ('setup_code', models.CharField(blank=True, max_length=1)),
                ('attack', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('attack_range', models.CharField(blank=True, max_length=3)),
                ('hull', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shields', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('agility', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=30)),
                ('initiative', models.PositiveSmallIntegerField(default=2)),
                ('bonus_xp', models.PositiveSmallIntegerField(default=0)),
                ('path', models.CharField(choices=[('F', 'Force User'), ('A', 'Ace')], default='A', max_length=1)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilots', to='campaign.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='PilotShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('chassis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pilot_ship', to='xwtools.chassis')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.pilot')),
            ],
        ),
        migrations.CreateModel(
            name='PlayableShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_value', models.SmallIntegerField(default=0)),
                ('progression', models.CharField(choices=[('d', 'Default'), ('h', 'HWK-290')], default='d', max_length=1)),
                ('chassis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwtools.chassis')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('V', 'Victory'), ('F', 'Failure'), ('U', 'Unresolved')], default='U', max_length=1)),
                ('bonus_1_achieved', models.BooleanField(default=False)),
                ('bonus_2_achieved', models.BooleanField(default=False)),
                ('penalty_received', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='SessionPilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative', models.PositiveSmallIntegerField(default=2)),
                ('hits', models.SmallIntegerField(blank=True, default=0)),
                ('assists', models.SmallIntegerField(blank=True, default=0)),
                ('guards', models.SmallIntegerField(blank=True, default=0)),
                ('emplacements', models.SmallIntegerField(blank=True, default=0)),
                ('bonus', models.SmallIntegerField(blank=True, default=0)),
                ('penalty', models.SmallIntegerField(blank=True, default=0)),
                ('status', models.CharField(choices=[('P', 'Not Flown'), ('V', 'Victory'), ('F', 'Ejected - Half XP'), ('N', 'Ejected - No XP'), ('H', 'Ejected - Lost Upgrade'), ('C', 'Ejected - Lost Talent'), ('K', 'Killed In Action')], default='P', max_length=1)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.pilot')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.session')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.pilotship')),
            ],
        ),
        migrations.CreateModel(
            name='SessionEnemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(default='', max_length=30)),
                ('level', models.SmallIntegerField(choices=[(1, 'Basic'), (2, 'Elite'), (3, 'In 3'), (4, 'In 4'), (5, 'In 5')], default=1)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.enemypilot')),
                ('flight_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.flightgroup')),
                ('killed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kills', to='campaign.sessionpilot')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.session')),
            ],
            options={
                'ordering': ['flight_group', '-level'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='enemies',
            field=models.ManyToManyField(through='campaign.SessionEnemy', to='campaign.EnemyPilot'),
        ),
        migrations.AddField(
            model_name='session',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.mission'),
        ),
        migrations.AddField(
            model_name='session',
            name='pilots',
            field=models.ManyToManyField(related_name='sessions', through='campaign.SessionPilot', to='campaign.Pilot'),
        ),
        migrations.CreateModel(
            name='Rulebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('start_init', models.PositiveSmallIntegerField(default=2)),
                ('ship_cost', models.PositiveSmallIntegerField(default=5)),
                ('upgrade_logic', models.PositiveSmallIntegerField(choices=[(1, 'HotAC'), (2, 'Test')])),
                ('initiative_progression', models.PositiveSmallIntegerField(choices=[(1, 'HotAC'), (2, 'Test')])),
                ('initiative_cost', models.PositiveSmallIntegerField(default=3)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('faction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xwtools.faction')),
                ('ships', models.ManyToManyField(through='campaign.PlayableShip', to='xwtools.Chassis')),
                ('starter_mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starts', to='campaign.mission')),
            ],
        ),
        migrations.AddField(
            model_name='playableship',
            name='rulebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.rulebook'),
        ),
        migrations.CreateModel(
            name='PilotUpgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('E', 'Equipped'), ('U', 'Unequipped'), ('X', 'Lost')], default='E', max_length=1)),
                ('cost', models.PositiveSmallIntegerField()),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xwtools.card')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='campaign.pilot')),
            ],
            options={
                'ordering': ['card__type', 'status'],
            },
        ),
        migrations.AddField(
            model_name='pilot',
            name='ships',
            field=models.ManyToManyField(related_name='pilot_character', through='campaign.PilotShip', to='xwtools.Chassis'),
        ),
        migrations.AddField(
            model_name='pilot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mission',
            name='features',
            field=models.ManyToManyField(blank=True, to='campaign.MissionFeature'),
        ),
        migrations.AddField(
            model_name='mission',
            name='rulebook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.rulebook'),
        ),
        migrations.AddField(
            model_name='flightgroup',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_groups', to='campaign.mission'),
        ),
        migrations.CreateModel(
            name='FGSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('A', 'Add'), ('R', 'Replace')], default='A', max_length=1)),
                ('players', models.SmallIntegerField(default=1)),
                ('init', models.SmallIntegerField(default=1)),
                ('elite', models.BooleanField(default=False)),
                ('chassis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xwtools.chassis')),
                ('enemy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.enemypilot')),
                ('flight_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_members', to='campaign.flightgroup')),
            ],
            options={
                'verbose_name': 'Squad Member',
                'verbose_name_plural': 'Squad Members',
            },
        ),
        migrations.AddField(
            model_name='enemyability',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='campaign.enemypilot'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='deck',
            field=models.ManyToManyField(to='campaign.Mission'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='exclude_random',
            field=models.ManyToManyField(blank=True, to='xwtools.Chassis'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='gm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_gm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='players',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='rulebook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.rulebook'),
        ),
        migrations.CreateModel(
            name='Ally',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=35)),
                ('initiative', models.PositiveSmallIntegerField(default=1)),
                ('abilities', models.ManyToManyField(blank=True, limit_choices_to={'ai_description__isnull': False}, to='xwtools.Card')),
                ('chassis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwtools.chassis')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allies', to='campaign.mission')),
            ],
            options={
                'verbose_name_plural': 'Allies',
            },
        ),
        migrations.CreateModel(
            name='AIPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('U', 'System Phase'), ('T', 'Target'), ('A', 'Action')], max_length=1)),
                ('step', models.PositiveSmallIntegerField(default=1)),
                ('desc', models.CharField(max_length=75)),
                ('ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='campaign.ai')),
            ],
            options={
                'verbose_name_plural': 'AI Priorities',
                'ordering': ['-type', 'step'],
            },
        ),
        migrations.CreateModel(
            name='AIManeuver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arc', models.CharField(choices=[('BE', 'Bullseye'), ('FR', 'Front (Right)'), ('RF', 'Right (Front)'), ('RA', 'Right (Rear)'), ('AR', 'Rear (Right)'), ('FL', 'Front (Left)'), ('LF', 'Left (Front)'), ('LA', 'Left (Rear)'), ('AL', 'Rear (Left)'), ('SP', 'Special')], max_length=2)),
                ('range', models.CharField(choices=[('1', 'R1/R2 Closing'), ('2', 'R3/R2 Fleeing'), ('3', 'R4+'), ('4', 'Stressed'), ('5', 'Hyperspace'), ('6', 'Decloak')], max_length=1)),
                ('ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.ai')),
                ('roll_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_1', to='xwtools.dialmaneuver')),
                ('roll_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_2', to='xwtools.dialmaneuver')),
                ('roll_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_3', to='xwtools.dialmaneuver')),
                ('roll_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_4', to='xwtools.dialmaneuver')),
                ('roll_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_5', to='xwtools.dialmaneuver')),
                ('roll_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_6', to='xwtools.dialmaneuver')),
            ],
            options={
                'ordering': ['arc', 'range'],
            },
        ),
        migrations.AddField(
            model_name='ai',
            name='rulebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.rulebook'),
        ),
        migrations.AddIndex(
            model_name='pilotship',
            index=models.Index(fields=['active'], name='campaign_pi_active_14aaf2_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['story', 'sequence'], name='campaign_mi_story_16a802_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['rulebook'], name='campaign_mi_ruleboo_76e770_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['player_vp'], name='campaign_mi_player__753ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='fgsetup',
            index=models.Index(fields=['players'], name='campaign_fg_players_1e9636_idx'),
        ),
        migrations.AddIndex(
            model_name='fgsetup',
            index=models.Index(fields=['init'], name='campaign_fg_init_e0ba35_idx'),
        ),
    ]
