# Generated by Django 3.0.6 on 2020-05-17 22:27

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flee', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('victory', models.PositiveSmallIntegerField()),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(max_length=25)),
                ('long_desc', models.CharField(max_length=60)),
                ('xp', models.SmallIntegerField()),
                ('team', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('story', models.CharField(max_length=30)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('territory', models.CharField(choices=[('F', 'Friendly'), ('N', 'Neutral'), ('H', 'Hostile')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=30)),
                ('total_xp', models.PositiveSmallIntegerField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start_xp', models.PositiveSmallIntegerField(default=0)),
                ('playable', models.BooleanField(default=True)),
                ('dial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Dial')),
            ],
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Configuration'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('GNR', 'Gunner'), ('ILC', 'Illicit'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TLN', 'Talent'), ('TCH', 'Tech'), ('TTL', 'Title'), ('TRP', 'Torpedo'), ('TRT', 'Turret'), ('SHP', 'Ship'), ('PLT', 'Pilot'), ('THR', 'Initiative'), ('FCH', 'Force Charge'), ('CHR', 'Charge'), ('WLD', 'Wildcard')], max_length=3)),
                ('type2', models.CharField(blank=True, choices=[('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Configuration'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('GNR', 'Gunner'), ('ILC', 'Illicit'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TLN', 'Talent'), ('TCH', 'Tech'), ('TTL', 'Title'), ('TRP', 'Torpedo'), ('TRT', 'Turret'), ('SHP', 'Ship'), ('PLT', 'Pilot'), ('THR', 'Initiative'), ('FCH', 'Force Charge'), ('CHR', 'Charge'), ('WLD', 'Wildcard')], default=None, max_length=3, null=True)),
                ('cost', models.PositiveSmallIntegerField()),
                ('charges', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['type', '-type2', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TreeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat', models.PositiveSmallIntegerField()),
                ('cost', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Configuration'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('GNR', 'Gunner'), ('ILC', 'Illicit'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TLN', 'Talent'), ('TCH', 'Tech'), ('TTL', 'Title'), ('TRP', 'Torpedo'), ('TRT', 'Turret'), ('SHP', 'Ship'), ('PLT', 'Pilot'), ('THR', 'Initiative'), ('FCH', 'Force Charge'), ('CHR', 'Charge'), ('WLD', 'Wildcard')], max_length=3)),
                ('type2', models.CharField(blank=True, choices=[('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Configuration'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('GNR', 'Gunner'), ('ILC', 'Illicit'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TLN', 'Talent'), ('TCH', 'Tech'), ('TTL', 'Title'), ('TRP', 'Torpedo'), ('TRT', 'Turret'), ('SHP', 'Ship'), ('PLT', 'Pilot'), ('THR', 'Initiative'), ('FCH', 'Force Charge'), ('CHR', 'Charge'), ('WLD', 'Wildcard')], default=None, max_length=3, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.TreeSlot')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Ship')),
            ],
            options={
                'ordering': ['threat', 'id', 'cost'],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat', models.PositiveSmallIntegerField()),
                ('cost', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Configuration'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('GNR', 'Gunner'), ('ILC', 'Illicit'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TLN', 'Talent'), ('TCH', 'Tech'), ('TTL', 'Title'), ('TRP', 'Torpedo'), ('TRT', 'Turret'), ('SHP', 'Ship'), ('PLT', 'Pilot'), ('THR', 'Initiative'), ('FCH', 'Force Charge'), ('CHR', 'Charge'), ('WLD', 'Wildcard')], max_length=3)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Slot')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Ship')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('outcome', models.CharField(choices=[('V', 'Victory'), ('F', 'Failure'), ('U', 'Unresolved')], default='U', max_length=1)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Mission')),
                ('pilots', models.ManyToManyField(to='campaign.Pilot')),
            ],
        ),
        migrations.CreateModel(
            name='PilotShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Pilot')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Ship')),
                ('unlocked', models.ManyToManyField(to='campaign.Slot')),
            ],
        ),
        migrations.AddField(
            model_name='pilot',
            name='upgrades',
            field=models.ManyToManyField(to='campaign.Upgrade'),
        ),
        migrations.AddField(
            model_name='pilot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DialManeuver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.PositiveSmallIntegerField()),
                ('move', models.CharField(choices=[('S', 'Straight'), ('B', 'Bank'), ('T', 'Turn'), ('KT', 'K-Turn'), ('TR', 'Tallon Roll'), ('SL', 'Sloop'), ('RB', 'Reverse Bank'), ('SS', 'Stationary')], max_length=3)),
                ('bearing', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=1, null=True)),
                ('color', models.CharField(choices=[('B', 'Blue'), ('W', 'White'), ('R', 'Red')], default='W', max_length=1)),
                ('dial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Dial')),
            ],
        ),
        migrations.CreateModel(
            name='AIManeuver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('BE', 'Bullseye'), ('FR', 'Front (Right)'), ('RF', 'Right (Front)'), ('RA', 'Right (Rear)'), ('AR', 'Rear (Right)'), ('FL', 'Front (Left)'), ('LF', 'Left (Front)'), ('LA', 'Left (Rear)'), ('AL', 'Rear (Left)')], max_length=2)),
                ('range', models.CharField(choices=[('1', 'R1/R2 Closing'), ('2', 'R3/R2 Fleeing'), ('3', 'R4+'), ('4', 'Stressed')], max_length=1)),
                ('ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.AI')),
                ('roll_1', smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', on_delete=django.db.models.deletion.CASCADE, related_name='roll_1', to='campaign.DialManeuver')),
                ('roll_2', smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', on_delete=django.db.models.deletion.CASCADE, related_name='roll_2', to='campaign.DialManeuver')),
                ('roll_3', smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', on_delete=django.db.models.deletion.CASCADE, related_name='roll_3', to='campaign.DialManeuver')),
                ('roll_4', smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', on_delete=django.db.models.deletion.CASCADE, related_name='roll_4', to='campaign.DialManeuver')),
                ('roll_5', smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', on_delete=django.db.models.deletion.CASCADE, related_name='roll_5', to='campaign.DialManeuver')),
                ('roll_6', smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', on_delete=django.db.models.deletion.CASCADE, related_name='roll_6', to='campaign.DialManeuver')),
            ],
        ),
        migrations.AddField(
            model_name='ai',
            name='dial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Dial'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.PositiveSmallIntegerField()),
                ('threat', models.SmallIntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.Event')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Pilot')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Session')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dialmaneuver',
            constraint=models.UniqueConstraint(fields=('dial', 'speed', 'move', 'bearing'), name='dial_maneuver'),
        ),
        migrations.AddConstraint(
            model_name='aimaneuver',
            constraint=models.UniqueConstraint(fields=('ai', 'direction', 'range'), name='ai_maneuver'),
        ),
    ]
