# Generated by Django 3.0.6 on 2020-06-10 20:21

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('xwtools', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flee', models.PositiveSmallIntegerField(default=0)),
                ('version', models.CharField(choices=[('f7', 'FGA 0.7')], default='f7', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'AI',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('start_init', models.SmallIntegerField(default=2)),
                ('ship_cost', models.SmallIntegerField(default=5)),
                ('upgrade_logic', models.IntegerField(choices=[(1, 'HotAC')])),
                ('initiative_cost', models.SmallIntegerField(default=3)),
                ('initiative_sq', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnemyAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, 'Basic'), (2, 'Elite'), (3, 'In 3'), (4, 'In 4'), (5, 'In 5')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='EnemyPilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwtools.Chassis')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwtools.Faction')),
                ('upgrades', models.ManyToManyField(through='campaign.EnemyAbility', to='xwtools.Upgrade')),
            ],
        ),
        migrations.CreateModel(
            name='FlightGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('arrival', models.SmallIntegerField(default=1)),
                ('vector', models.CharField(max_length=3)),
                ('orders', models.CharField(choices=[('A', 'Attack'), ('S', 'Strike'), ('E', 'Escort'), ('X', 'Special')], default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('victory', models.PositiveSmallIntegerField()),
                ('ship_initiative', models.BooleanField(default=False)),
                ('pool_xp', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.Campaign')),
                ('gm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_gm', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('story', models.CharField(max_length=30)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('territory', models.CharField(choices=[('F', 'Friendly'), ('N', 'Neutral'), ('H', 'Hostile')], max_length=1)),
                ('enemy_faction', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xwtools.Faction')),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=30)),
                ('initiative', models.PositiveSmallIntegerField(default=2)),
                ('path', models.CharField(choices=[('F', 'Force User'), ('A', 'Ace')], default='A', max_length=1)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('outcome', models.CharField(choices=[('V', 'Victory'), ('F', 'Failure'), ('U', 'Unresolved')], default='U', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SessionEnemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, 'Basic'), (2, 'Elite'), (3, 'In 3'), (4, 'In 4'), (5, 'In 5')], default=1)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.EnemyPilot')),
                ('flight_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.FlightGroup')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Session')),
            ],
            options={
                'ordering': ['flight_group', '-level'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='enemies',
            field=models.ManyToManyField(through='campaign.SessionEnemy', to='campaign.EnemyPilot'),
        ),
        migrations.AddField(
            model_name='session',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Game'),
        ),
        migrations.AddField(
            model_name='session',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Mission'),
        ),
        migrations.AddField(
            model_name='session',
            name='pilots',
            field=models.ManyToManyField(related_name='sessions', to='campaign.Pilot'),
        ),
        migrations.CreateModel(
            name='PlayerShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_value', models.SmallIntegerField(default=0)),
                ('progression', models.CharField(choices=[('d', 'Default'), ('h', 'HWK-290')], default='d', max_length=1)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('chassis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwtools.Chassis')),
            ],
        ),
        migrations.CreateModel(
            name='PilotUpgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('copies', models.PositiveSmallIntegerField(default=1)),
                ('lost', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='campaign.Pilot')),
            ],
        ),
        migrations.CreateModel(
            name='PilotShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative', models.PositiveSmallIntegerField(default=2)),
                ('chassis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pilot_ship', to='xwtools.Chassis')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Pilot')),
            ],
        ),
        migrations.AddField(
            model_name='pilot',
            name='ships',
            field=models.ManyToManyField(related_name='pilot_character', through='campaign.PilotShip', to='xwtools.Chassis'),
        ),
        migrations.AddField(
            model_name='pilot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flightgroup',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_groups', to='campaign.Mission'),
        ),
        migrations.CreateModel(
            name='FGSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('A', 'Add'), ('R', 'Replace')], default='A', max_length=1)),
                ('players', models.SmallIntegerField(default=1)),
                ('init', models.SmallIntegerField(default=1)),
                ('elite', models.BooleanField(default=False)),
                ('chassis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xwtools.Chassis')),
                ('flight_group', smart_selects.db_fields.ChainedForeignKey(chained_field='mission', chained_model_field='mission', on_delete=django.db.models.deletion.CASCADE, related_name='squad_members', to='campaign.FlightGroup')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Mission')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(max_length=25)),
                ('long_desc', models.CharField(max_length=120)),
                ('xp', models.SmallIntegerField(default=1)),
                ('team', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='campaign.Campaign')),
            ],
        ),
        migrations.AddField(
            model_name='enemyability',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='campaign.EnemyPilot'),
        ),
        migrations.AddField(
            model_name='enemyability',
            name='upgrade',
            field=models.ForeignKey(limit_choices_to={'ai_description__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='xwtools.Upgrade'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ships',
            field=models.ManyToManyField(through='campaign.PlayerShip', to='xwtools.Chassis'),
        ),
        migrations.CreateModel(
            name='AIManeuver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arc', models.CharField(choices=[('BE', 'Bullseye'), ('FR', 'Front (Right)'), ('RF', 'Right (Front)'), ('RA', 'Right (Rear)'), ('AR', 'Rear (Right)'), ('FL', 'Front (Left)'), ('LF', 'Left (Front)'), ('LA', 'Left (Rear)'), ('AL', 'Rear (Left)')], max_length=2)),
                ('range', models.CharField(choices=[('1', 'R1/R2 Closing'), ('2', 'R3/R2 Fleeing'), ('3', 'R4+'), ('4', 'Stressed'), ('5', 'Fleeing')], max_length=1)),
                ('ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.AI')),
                ('roll_1', smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', on_delete=django.db.models.deletion.CASCADE, related_name='roll_1', to='xwtools.DialManeuver')),
                ('roll_2', smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', on_delete=django.db.models.deletion.CASCADE, related_name='roll_2', to='xwtools.DialManeuver')),
                ('roll_3', smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', on_delete=django.db.models.deletion.CASCADE, related_name='roll_3', to='xwtools.DialManeuver')),
                ('roll_4', smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', on_delete=django.db.models.deletion.CASCADE, related_name='roll_4', to='xwtools.DialManeuver')),
                ('roll_5', smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', on_delete=django.db.models.deletion.CASCADE, related_name='roll_5', to='xwtools.DialManeuver')),
                ('roll_6', smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', on_delete=django.db.models.deletion.CASCADE, related_name='roll_6', to='xwtools.DialManeuver')),
            ],
        ),
        migrations.AddField(
            model_name='ai',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign'),
        ),
        migrations.AddField(
            model_name='ai',
            name='dial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwtools.Dial'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.PositiveSmallIntegerField()),
                ('threat', models.SmallIntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.Event')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Pilot')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='campaign.Session')),
                ('target', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.SessionEnemy')),
            ],
        ),
    ]
