# Generated by Django 3.0.6 on 2020-05-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aimaneuver',
            name='ai_maneuver',
        ),
        migrations.RemoveConstraint(
            model_name='dialmaneuver',
            name='dial_maneuver',
        ),
        migrations.RenameField(
            model_name='aimaneuver',
            old_name='direction',
            new_name='arc',
        ),
        migrations.RenameField(
            model_name='dialmaneuver',
            old_name='bearing',
            new_name='direction',
        ),
        migrations.AlterField(
            model_name='dial',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
