# Generated by Django 3.0.6 on 2020-05-26 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0002_auto_20200526_2239'),
        ('campaign', '0001_squashed_0032_auto_20200525_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadmember',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Mission'),
        ),
        migrations.AlterField(
            model_name='squadron',
            name='chassis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwtools.Chassis'),
        ),
    ]
