# Generated by Django 2.2.1 on 2019-06-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_squashed_0013_auto_20190520_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='turn',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='victory',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='xp',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='sequence',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(),
        ),
    ]