# Generated by Django 2.2.1 on 2019-06-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20190601_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='total_xp',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
