# Generated by Django 3.0.6 on 2020-05-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20200526_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemyupgrade',
            name='type',
            field=models.CharField(choices=[('TLN', 'Talent'), ('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Config'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('PLT', 'Pilot'), ('GNR', 'Gunner'), ('ILC', 'Illicit`'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TCH', 'Tech'), ('TRP', 'Torpedo'), ('TTL', 'Title'), ('TRT', 'Turret'), ('SHP', 'Ship')], max_length=3),
        ),
    ]
