# Generated by Django 3.0.6 on 2020-06-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20200610_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUpgrades',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('base_id', models.IntegerField()),
                ('base', models.CharField(choices=[('P', 'Pilot'), ('U', 'Upgrade')], max_length=1)),
                ('name', models.CharField(max_length=30)),
                ('cost', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('ai_description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('TLN', 'Talent'), ('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Config'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('PLT', 'Pilot'), ('GNR', 'Gunner'), ('ILC', 'Illicit`'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TCH', 'Tech'), ('TRP', 'Torpedo'), ('TTL', 'Title'), ('TRT', 'Turret'), ('SHP', 'Ship')], max_length=3)),
                ('type2', models.CharField(blank=True, choices=[('TLN', 'Talent'), ('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Config'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('PLT', 'Pilot'), ('GNR', 'Gunner'), ('ILC', 'Illicit`'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TCH', 'Tech'), ('TRP', 'Torpedo'), ('TTL', 'Title'), ('TRT', 'Turret'), ('SHP', 'Ship')], default=None, max_length=3, null=True)),
                ('charges', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('force', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'campaign_gameupgrades_v',
                'managed': False,
            },
        ),
    ]
