# Generated by Django 3.0.6 on 2020-05-18 20:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20200518_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialmaneuver',
            options={'ordering': ['-speed', django.db.models.expressions.CombinedExpression(django.db.models.expressions.Case(django.db.models.expressions.When(bearing='S', then=django.db.models.expressions.Value(2)), django.db.models.expressions.When(bearing='B', then=django.db.models.expressions.Value(3)), django.db.models.expressions.When(bearing='T', then=django.db.models.expressions.Value(4)), django.db.models.expressions.When(bearing='SL', then=django.db.models.expressions.Value(6)), django.db.models.expressions.When(bearing='KT', then=django.db.models.expressions.Value(8)), output_field=models.SmallIntegerField()), '*', django.db.models.expressions.Case(django.db.models.expressions.When(direction='L', then=django.db.models.expressions.Value(-1)), default=django.db.models.expressions.Value(1), output_field=models.SmallIntegerField()))]},
        ),
        migrations.AlterField(
            model_name='dialmaneuver',
            name='dial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maneuvers', to='campaign.Dial'),
        ),
    ]
