# Generated by Django 3.0.6 on 2020-05-28 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0006_auto_20200528_0139'),
        ('campaign', '0003_auto_20200528_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemyability',
            name='upgrade',
            field=models.ForeignKey(limit_choices_to={'ai_description__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='xwtools.Upgrade'),
        ),
        migrations.AlterField(
            model_name='enemypilot',
            name='upgrades',
            field=models.ManyToManyField(through='campaign.EnemyAbility', to='xwtools.Upgrade'),
        ),
    ]
