# Generated by Django 2.2.1 on 2019-06-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_pilot_upgrades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrade',
            name='charges',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
