# Generated by Django 2.2.1 on 2019-06-01 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_auto_20190601_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upgrade',
            name='ability',
        ),
    ]
