# Generated by Django 3.0.6 on 2020-05-29 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0008_auto_20200529_0241'),
        ('campaign', '0005_delete_enemyupgrade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SquadMember',
            new_name='FGSetup',
        ),
        migrations.CreateModel(
            name='SessionEnemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, 'Basic'), (2, 'Elite'), (3, 'In 3'), (4, 'In 4'), (5, 'In 5')], default=1)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.EnemyPilot')),
                ('flight_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.FlightGroup')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Session')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='enemies',
            field=models.ManyToManyField(through='campaign.SessionEnemy', to='campaign.EnemyPilot'),
        ),
    ]
