# Generated by Django 3.0.6 on 2020-06-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_pilotupgrade_equipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilotupgrade',
            name='equipped',
        ),
        migrations.RemoveField(
            model_name='pilotupgrade',
            name='lost',
        ),
        migrations.AddField(
            model_name='pilotupgrade',
            name='status',
            field=models.CharField(choices=[('E', 'Equipped'), ('U', 'Unequipped'), ('L', 'Lost')], default='E', max_length=1),
        ),
    ]
