# Generated by Django 3.0.6 on 2020-05-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_auto_20200519_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='faction',
            field=models.CharField(choices=[('RA', 'Rebel Alliance'), ('GE', 'Galactic Empire'), ('SV', 'Scum and Villainy'), ('RS', 'Resistance'), ('FO', 'First Order'), ('GR', 'Republic'), ('SE', 'Seperatist')], default='RA', max_length=2),
        ),
    ]
