# Generated by Django 3.0.6 on 2020-05-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_auto_20200529_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionenemy',
            name='elite',
            field=models.BooleanField(default=False),
        ),
    ]
