# Generated by Django 3.0.6 on 2020-06-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0002_auto_20200610_2143'),
        ('campaign', '0007_auto_20200612_2248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campaign',
            new_name='Rulebook',
        ),
        migrations.RenameField(
            model_name='ai',
            old_name='campaign',
            new_name='rulebook',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='campaign',
            new_name='rulebook',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='campaign',
            new_name='rulebook',
        ),
        migrations.RenameField(
            model_name='playership',
            old_name='campaign',
            new_name='rulebook',
        ),
    ]
