# Generated by Django 3.0.6 on 2020-05-20 02:24

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0002_auto_20200520_0224'),
        ('campaign', '0007_ship_faction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_xp', models.PositiveSmallIntegerField(default=0)),
                ('playable', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ai',
            name='dial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwtools.Dial'),
        ),
        migrations.AlterField(
            model_name='aimaneuver',
            name='roll_1',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', on_delete=django.db.models.deletion.CASCADE, related_name='roll_1', to='xwtools.DialManeuver'),
        ),
        migrations.AlterField(
            model_name='aimaneuver',
            name='roll_2',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', on_delete=django.db.models.deletion.CASCADE, related_name='roll_2', to='xwtools.DialManeuver'),
        ),
        migrations.AlterField(
            model_name='aimaneuver',
            name='roll_3',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', on_delete=django.db.models.deletion.CASCADE, related_name='roll_3', to='xwtools.DialManeuver'),
        ),
        migrations.AlterField(
            model_name='aimaneuver',
            name='roll_4',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', on_delete=django.db.models.deletion.CASCADE, related_name='roll_4', to='xwtools.DialManeuver'),
        ),
        migrations.AlterField(
            model_name='aimaneuver',
            name='roll_5',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', on_delete=django.db.models.deletion.CASCADE, related_name='roll_5', to='xwtools.DialManeuver'),
        ),
        migrations.AlterField(
            model_name='aimaneuver',
            name='roll_6',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', on_delete=django.db.models.deletion.CASCADE, related_name='roll_6', to='xwtools.DialManeuver'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='upgrades',
            field=models.ManyToManyField(to='xwtools.Upgrade'),
        ),
        migrations.AlterField(
            model_name='pilotship',
            name='unlocked',
            field=models.ManyToManyField(to='xwtools.Slot'),
        ),
    ]
