# Generated by Django 3.0.6 on 2020-05-20 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0002_auto_20200520_0224'),
        ('campaign', '0008_auto_20200520_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ships',
            field=models.ManyToManyField(through='campaign.CampaignShip', to='xwtools.Ship'),
        ),
        migrations.AddField(
            model_name='campaignship',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaignship',
            name='ship',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xwtools.Ship'),
            preserve_default=False,
        ),
    ]
