# Generated by Django 3.0.6 on 2020-05-29 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_remove_sessionenemy_elite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilot',
            name='campaign',
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('victory', models.PositiveSmallIntegerField()),
                ('ship_initiative', models.BooleanField(default=False)),
                ('pool_xp', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.Campaign')),
                ('gm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_gm', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pilot',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.Game'),
        ),
    ]
