# Generated by Django 3.0.6 on 2020-06-21 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_auto_20200621_1652'),
    ]

    operations = [
        migrations.RenameModel(old_name='GameUpgrade', new_name='CampaignUpgrade'),

        migrations.RenameModel(old_name='Game', new_name='Campaign'),

        migrations.RenameField(
            model_name='pilot',
            old_name='game',
            new_name='campaign'
        ),
        migrations.RenameField(
            model_name='session',
            old_name='game',
            new_name='campaign'
        ),

        migrations.AlterField(
            model_name='pilotupgrade',
            name='upgrade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.CampaignUpgrade'),
        ),

    ]
