# Generated by Django 3.0.6 on 2020-05-29 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_auto_20200529_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='campaign',
        ),
        migrations.AddField(
            model_name='session',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.Game'),
            preserve_default=False,
        ),
    ]
