# Generated by Django 2.2.1 on 2019-06-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_treeslot_type2'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team',
            field=models.BooleanField(default=True),
        ),
    ]
