# Generated by Django 3.0.6 on 2020-05-20 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_auto_20200520_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilotship',
            name='ship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.CampaignShip'),
        ),
    ]
