# Generated by Django 2.2.1 on 2020-05-16 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_event_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIManeuver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('BE', 'Bullseye'), ('FR', 'Forward Right'), ('FL', 'Forward Left'), ('FF', 'Full Forward'), ('AR', 'Aft Right'), ('AL', 'Aft Left'), ('AF', 'Full Aft')], max_length=2)),
                ('range', models.CharField(choices=[('1', 'R1/R2 Closing'), ('2', 'R3/R2 Fleeing'), ('3', 'R4+'), ('4', 'Stressed')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Dial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='ship',
            name='playable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='start_xp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DialManeuvers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move', models.CharField(choices=[('BL', 'Bank Left'), ('BR', 'Bank Right'), ('SS', 'Stationary'), ('TRL', 'Tallon Roll Left'), ('TRL', 'Tallon Roll Right'), ('TL', 'Turn Left'), ('TR', 'Turn Right'), ('RBL', 'Reverse Bank Left'), ('RBR', 'Reverse Bank Right'), ('SL', 'Sloop Left'), ('SR', 'Sloop Right'), ('ST', 'Straight')], max_length=3)),
                ('color', models.CharField(choices=[('B', 'Blue'), ('W', 'White'), ('R', 'Red')], default='W', max_length=1)),
                ('speed', models.PositiveSmallIntegerField()),
                ('dial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Dial')),
            ],
        ),
        migrations.AddField(
            model_name='dial',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Ship'),
        ),
        migrations.CreateModel(
            name='AI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flee', models.PositiveSmallIntegerField(default=0)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Ship')),
            ],
        ),
    ]
