# Generated by Django 3.0.6 on 2020-05-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_auto_20200529_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ai',
            options={'verbose_name_plural': 'AI'},
        ),
    ]
