# Generated by Django 3.2.4 on 2021-06-08 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_auto_20210608_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.SmallIntegerField(default=0)),
                ('assists', models.SmallIntegerField(default=0)),
                ('guardians', models.SmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('P', 'Not Flown'), ('V', 'Victory'), ('F', 'Ejected - Half XP'), ('N', 'Ejected - No XP'), ('H', 'Ejected - Lost Upgrade'), ('C', 'Ejected - Lost Talent'), ('K', 'Killed In Action')], default='P', max_length=1)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.pilot')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.session')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.pilotship')),
            ],
        ),
        migrations.AddField(
            model_name='sessionenemy',
            name='killed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kills', to='campaign.sessionpilot'),
        ),

        migrations.RemoveField(
            model_name='session',
            name='pilots'
        ),

        migrations.AddField(
            model_name='session',
            name='pilots',
            field=models.ManyToManyField(through='campaign.SessionPilot', to='campaign.Pilot'),
        ),
    ]
