# Generated by Django 2.2.1 on 2020-05-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_auto_20200516_1523'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DialManeuvers',
            new_name='DialManeuver',
        ),
    ]
