# Generated by Django 3.0.6 on 2020-05-22 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_auto_20200520_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignship',
            old_name='ship',
            new_name='chassis',
        ),
    ]
