# Generated by Django 3.2.4 on 2021-06-08 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_auto_20210608_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='pilots',
            field=models.ManyToManyField(related_name='sessions', through='campaign.SessionPilot', to='campaign.Pilot'),
        ),
        migrations.AlterField(
            model_name='sessionenemy',
            name='killed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kills', to='campaign.sessionpilot'),
        ),
    ]
