# Generated by Django 2.2.1 on 2020-05-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_auto_20200516_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialmaneuver',
            name='move',
            field=models.CharField(choices=[('BL', 'Bank Left'), ('BR', 'Bank Right'), ('SS', 'Stationary'), ('TRL', 'Tallon Roll Left'), ('TRL', 'Tallon Roll Right'), ('TL', 'Turn Left'), ('TR', 'Turn Right'), ('RBL', 'Reverse Bank Left'), ('RBR', 'Reverse Bank Right'), ('SL', 'Sloop Left'), ('SR', 'Sloop Right'), ('ST', 'Straight'), ('KT', 'K-Turn')], max_length=3),
        ),
    ]
