# Generated by Django 3.2.4 on 2021-06-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0013_auto_20210608_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionenemy',
            name='callsign',
            field=models.CharField(default='', max_length=30),
        ),
    ]
