# Generated by Django 3.0.6 on 2020-05-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0013_achievement_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='target',
        ),
    ]
