# Generated by Django 2.2.1 on 2020-05-16 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0013_auto_20200516_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dial',
            name='ship',
        ),
        migrations.AddField(
            model_name='dial',
            name='name',
            field=models.CharField(default='TIE/LN Fighter', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ship',
            name='dial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.Dial'),
            preserve_default=False,
        ),
    ]
