# Generated by Django 2.2.1 on 2020-05-16 16:52

import campaign.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0014_auto_20200516_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ai',
            name='ship',
        ),
        migrations.AddField(
            model_name='ai',
            name='dial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.Dial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aimaneuver',
            name='ai',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.AI'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aimaneuver',
            name='roll_1',
            field=models.ForeignKey(default=1, limit_choices_to=campaign.models.AIManeuver.get_maneuvers, on_delete=django.db.models.deletion.CASCADE, to='campaign.DialManeuver'),
            preserve_default=False,
        ),
    ]
