# Generated by Django 3.0.6 on 2020-05-30 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0015_auto_20200530_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign'),
            preserve_default=False,
        ),
    ]
