# Generated by Django 2.2.1 on 2020-05-16 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0015_auto_20200516_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimaneuver',
            name='roll_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.DialManeuver'),
        ),
    ]
