# Generated by Django 3.0.6 on 2020-05-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0015_auto_20200522_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotship',
            name='init_3',
            field=models.CharField(blank=True, choices=[('FRC', 'Force'), ('TLN', 'Talent')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='pilotship',
            name='init_5',
            field=models.CharField(blank=True, choices=[('FRC', 'Force'), ('TLN', 'Talent')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='pilotship',
            name='init_6',
            field=models.CharField(blank=True, choices=[('FRC', 'Force'), ('TLN', 'Talent')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='squadron',
            name='progression',
            field=models.CharField(choices=[('d', 'Default'), ('h', 'HWK-290')], default='d', max_length=1),
        ),
    ]
