# Generated by Django 3.0.6 on 2020-05-16 17:45

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0016_auto_20200516_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimaneuver',
            name='roll_1',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.DialManeuver'),
            preserve_default=False,
        ),
    ]
