# Generated by Django 3.0.6 on 2020-05-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0016_auto_20200522_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilotship',
            name='init_3',
        ),
        migrations.RemoveField(
            model_name='pilotship',
            name='init_5',
        ),
        migrations.RemoveField(
            model_name='pilotship',
            name='init_6',
        ),
        migrations.AddField(
            model_name='pilot',
            name='init_3',
            field=models.CharField(choices=[('FRC', 'Force'), ('TLN', 'Talent')], default='TLN', max_length=3),
        ),
        migrations.AddField(
            model_name='pilot',
            name='init_5',
            field=models.CharField(choices=[('FRC', 'Force'), ('TLN', 'Talent')], default='TLN', max_length=3),
        ),
        migrations.AddField(
            model_name='pilot',
            name='init_6',
            field=models.CharField(choices=[('FRC', 'Force'), ('TLN', 'Talent')], default='TLN', max_length=3),
        ),
    ]
