# Generated by Django 3.2.4 on 2021-06-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0016_auto_20210610_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='bonus_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='bonus_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='penalty',
            field=models.TextField(blank=True, null=True),
        ),
    ]
