# Generated by Django 3.0.6 on 2020-05-30 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0010_chassis_size'),
        ('campaign', '0016_event_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_xp', models.PositiveSmallIntegerField(default=10)),
                ('progression', models.CharField(choices=[('d', 'Default'), ('h', 'HWK-290')], default='d', max_length=1)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('chassis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwtools.Chassis')),
            ],
        ),
        migrations.DeleteModel(
            name='Squadron',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='ships',
            field=models.ManyToManyField(through='campaign.PlayerShip', to='xwtools.Chassis'),
        ),
    ]
