# Generated by Django 3.0.6 on 2020-05-30 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0017_auto_20200530_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign'),
            preserve_default=False,
        ),
    ]
