# Generated by Django 3.0.6 on 2020-05-16 18:12

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0017_auto_20200516_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimaneuver',
            name='roll_2',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roll_2', to='campaign.DialManeuver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aimaneuver',
            name='roll_3',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roll_3', to='campaign.DialManeuver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aimaneuver',
            name='roll_4',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roll_4', to='campaign.DialManeuver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aimaneuver',
            name='roll_5',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roll_5', to='campaign.DialManeuver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aimaneuver',
            name='roll_6',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roll_6', to='campaign.DialManeuver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dialmaneuver',
            name='direction',
            field=models.CharField(choices=[('S', 'Straight'), ('L', 'Left'), ('R', 'Right'), ('A', 'Advanced')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='aimaneuver',
            name='roll_1',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='ai', chained_model_field='dial', on_delete=django.db.models.deletion.CASCADE, related_name='roll_1', to='campaign.DialManeuver'),
        ),
        migrations.AlterField(
            model_name='dialmaneuver',
            name='move',
            field=models.CharField(choices=[('ST', 'Straight'), ('BL', 'Bank Left'), ('BR', 'Bank Right'), ('TL', 'Turn Left'), ('TR', 'Turn Right'), ('TRL', 'Tallon Roll Left'), ('TRL', 'Tallon Roll Right'), ('SS', 'Stationary'), ('RBL', 'Reverse Bank Left'), ('RBR', 'Reverse Bank Right'), ('SL', 'Sloop Left'), ('SR', 'Sloop Right'), ('KT', 'K-Turn')], max_length=3),
        ),
    ]
