# Generated by Django 3.0.6 on 2020-05-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0017_auto_20200522_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilot',
            name='init_3',
        ),
        migrations.RemoveField(
            model_name='pilot',
            name='init_5',
        ),
        migrations.RemoveField(
            model_name='pilot',
            name='init_6',
        ),
        migrations.AddField(
            model_name='pilot',
            name='path',
            field=models.CharField(choices=[('F', 'Force User'), ('A', 'Ace')], default='A', max_length=1),
        ),
    ]
