# Generated by Django 3.2.4 on 2021-06-10 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0017_auto_20210610_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionpilot',
            old_name='guardians',
            new_name='guards',
        ),
    ]
