# Generated by Django 3.0.6 on 2020-05-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0018_auto_20200523_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='pool_xp',
            field=models.BooleanField(default=False),
        ),
    ]
