# Generated by Django 3.0.6 on 2020-05-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0018_auto_20200516_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialmaneuver',
            name='move',
            field=models.CharField(choices=[('S', 'Straight'), ('B', 'Bank'), ('T', 'Turn'), ('KT', 'K-Turn'), ('TR', 'Tallon Roll'), ('SL', 'Sloop'), ('RB', 'Reverse Bank'), ('BL', 'Bank Left'), ('BR', 'Bank Right'), ('TL', 'Turn Left'), ('TR', 'Turn Right'), ('TRL', 'Tallon Roll Left'), ('TRL', 'Tallon Roll Right'), ('SS', 'Stationary'), ('RBL', 'Reverse Bank Left'), ('RBR', 'Reverse Bank Right'), ('SR', 'Sloop Right')], max_length=3),
        ),
    ]
