# Generated by Django 3.2.4 on 2021-06-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0018_rename_guardians_sessionpilot_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemypilot',
            name='random',
            field=models.BooleanField(default=True),
        ),
    ]
