# Generated by Django 3.0.6 on 2020-05-31 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0019_auto_20200530_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilotship',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='campaign.Pilot'),
        ),
    ]
