# Generated by Django 3.2.4 on 2021-06-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0019_enemypilot_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemypilot',
            name='name_override',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
