# Generated by Django 3.0.6 on 2020-05-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0019_auto_20200516_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialmaneuver',
            name='direction',
        ),
        migrations.AddField(
            model_name='dialmaneuver',
            name='bearing',
            field=models.CharField(choices=[('S', 'None'), ('L', 'Left'), ('R', 'Right')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='dialmaneuver',
            name='move',
            field=models.CharField(choices=[('S', 'Straight'), ('B', 'Bank'), ('T', 'Turn'), ('KT', 'K-Turn'), ('TR', 'Tallon Roll'), ('SL', 'Sloop'), ('RB', 'Reverse Bank'), ('SS', 'Stationary')], max_length=3),
        ),
    ]
