# Generated by Django 3.0.6 on 2020-05-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0020_remove_pilot_total_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimaneuver',
            name='range',
            field=models.CharField(choices=[('1', 'R1/R2 Closing'), ('2', 'R3/R2 Fleeing'), ('3', 'R4+'), ('4', 'Stressed'), ('5', 'Fleeing'), ('6', 'Decloaking')], max_length=1),
        ),
        migrations.AlterField(
            model_name='squadron',
            name='start_xp',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
