# Generated by Django 3.0.6 on 2020-05-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0020_auto_20200516_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialmaneuver',
            name='bearing',
            field=models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=1, null=True),
        ),
    ]
