# Generated by Django 3.0.6 on 2020-05-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0020_auto_20200531_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playership',
            name='start_xp',
        ),
        migrations.AddField(
            model_name='playership',
            name='xp_value',
            field=models.SmallIntegerField(default=-5),
        ),
    ]
