# Generated by Django 3.0.6 on 2020-05-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0021_auto_20200516_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimaneuver',
            name='direction',
            field=models.CharField(choices=[('BE', 'Bullseye'), ('FR', 'Forward (Right)'), ('RF', 'Right (Forward)'), ('RA', 'Right (Aft)'), ('AR', 'Aft (Right)'), ('FL', 'Forward (Left)'), ('LF', 'Left (Forward)'), ('LA', 'Left (Aft)'), ('AL', 'Aft (Left)')], max_length=2),
        ),
    ]
