# Generated by Django 3.0.6 on 2020-05-31 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0021_auto_20200531_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='campaign.Campaign'),
        ),
    ]
