# Generated by Django 3.0.6 on 2020-05-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0022_auto_20200523_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai',
            name='version',
            field=models.CharField(choices=[('f7', 'FGA 0.7')], default='f7', max_length=3),
        ),
    ]
