# Generated by Django 3.0.6 on 2020-05-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0022_auto_20200516_2017'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aimaneuver',
            constraint=models.UniqueConstraint(fields=('ai', 'direction', 'range'), name='ai_maneuver'),
        ),
        migrations.AddConstraint(
            model_name='dialmaneuver',
            constraint=models.UniqueConstraint(fields=('dial', 'speed', 'move', 'bearing'), name='dial_maneuver'),
        ),
    ]
