# Generated by Django 3.2.4 on 2021-06-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0022_aipriority_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aipriority',
            name='desc',
            field=models.CharField(max_length=75),
        ),
    ]
