# Generated by Django 3.2.4 on 2021-06-12 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0023_alter_aipriority_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimaneuver',
            options={'ordering': ['arc', 'range']},
        ),
        migrations.AddField(
            model_name='campaign',
            name='deck',
            field=models.ManyToManyField(to='campaign.Mission'),
        ),
        migrations.AddField(
            model_name='mission',
            name='rulebook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.rulebook'),
        ),
        migrations.AddField(
            model_name='mission',
            name='turns',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='aimaneuver',
            name='arc',
            field=models.CharField(choices=[('BE', 'Bullseye'), ('FR', 'Front (Right)'), ('RF', 'Right (Front)'), ('RA', 'Right (Rear)'), ('AR', 'Rear (Right)'), ('FL', 'Front (Left)'), ('LF', 'Left (Front)'), ('LA', 'Left (Rear)'), ('AL', 'Rear (Left)'), ('SS', 'Special')], max_length=2),
        ),
    ]
