# Generated by Django 3.0.6 on 2020-06-01 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0010_chassis_size'),
        ('campaign', '0023_auto_20200531_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='ships',
            field=models.ManyToManyField(through='campaign.PilotShip', to='xwtools.Chassis'),
        ),
        migrations.AlterField(
            model_name='pilotship',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Pilot'),
        ),
    ]
