# Generated by Django 3.0.6 on 2020-05-24 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0019_chassis_css'),
        ('campaign', '0023_ai_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnemyAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, 'Basic'), (2, 'Elite'), (3, 'IN 3+'), (4, 'IN 4+'), (5, 'IN 5+)')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='EnemyUpgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ability', models.CharField(max_length=240)),
                ('type', models.CharField(choices=[('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Configuration'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('GNR', 'Gunner'), ('ILC', 'Illicit'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TLN', 'Talent'), ('TCH', 'Tech'), ('TTL', 'Title'), ('TRP', 'Torpedo'), ('TRT', 'Turret'), ('SHP', 'Ship'), ('PLT', 'Pilot'), ('THR', 'Initiative'), ('FCH', 'Force Charge'), ('CHR', 'Charge'), ('WLD', 'Wildcard')], max_length=3)),
                ('charges', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EnemyPilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwtools.Chassis')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwtools.Faction')),
                ('upgrades', models.ManyToManyField(through='campaign.EnemyAbility', to='campaign.EnemyUpgrade')),
            ],
        ),
        migrations.AddField(
            model_name='enemyability',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.EnemyPilot'),
        ),
        migrations.AddField(
            model_name='enemyability',
            name='upgrade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.EnemyUpgrade'),
        ),
    ]
