# Generated by Django 3.2.4 on 2021-06-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0024_auto_20210612_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionpilot',
            name='emplacements',
            field=models.SmallIntegerField(default=0),
        ),
    ]
