# Generated by Django 3.0.6 on 2020-06-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0024_auto_20200601_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='pool_xp',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='ship_initiative',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='victory',
        ),
        migrations.RemoveField(
            model_name='pilotship',
            name='hull_upgrades',
        ),
        migrations.RemoveField(
            model_name='pilotship',
            name='shield_upgrades',
        ),
        migrations.AddField(
            model_name='campaign',
            name='ship_cost',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='playership',
            name='xp_value',
            field=models.SmallIntegerField(default=0),
        ),
    ]
