# Generated by Django 3.0.6 on 2020-05-24 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0019_chassis_css'),
        ('campaign', '0024_auto_20200524_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('arrival', models.SmallIntegerField(default=1)),
                ('vector', models.CharField(max_length=3)),
                ('orders', models.CharField(choices=[('A', 'Attack'), ('S', 'Strike'), ('X', 'Special')], default='S', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='enemy_faction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xwtools.Faction'),
        ),
        migrations.AlterField(
            model_name='enemyability',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'Basic'), (2, 'Elite'), (3, 'IN 3+'), (4, 'IN 4+'), (5, 'IN 5+')], default=1),
        ),
        migrations.AlterField(
            model_name='enemyability',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='campaign.EnemyPilot'),
        ),
        migrations.CreateModel(
            name='SquadMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('A', 'Add'), ('R', 'Replace')], max_length=1)),
                ('players', models.SmallIntegerField(default=1)),
                ('int', models.SmallIntegerField(default=1)),
                ('elite', models.BooleanField(default=False)),
                ('chassis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xwtools.Chassis')),
                ('flight_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_members', to='campaign.FlightGroup')),
            ],
        ),
    ]
