# Generated by Django 3.0.6 on 2020-05-25 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0019_chassis_css'),
        ('campaign', '0025_auto_20200524_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightgroup',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.Session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squadron',
            name='enemy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='squadmember',
            name='chassis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xwtools.Chassis'),
        ),
    ]
