# Generated by Django 3.2.4 on 2021-06-13 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0025_sessionpilot_emplacements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='rulebook',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='ship_initiative',
        ),
        migrations.RemoveField(
            model_name='pilotship',
            name='initiative',
        ),
        migrations.AlterField(
            model_name='pilot',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilots', to='campaign.campaign'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
