# Generated by Django 3.0.6 on 2020-06-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0025_auto_20200601_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='pilots',
            field=models.ManyToManyField(related_name='sessions', to='campaign.Pilot'),
        ),
    ]
