# Generated by Django 3.0.6 on 2020-05-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0026_auto_20200525_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemyability',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'Basic'), (2, 'Elite'), (3, 'In 3'), (4, 'In 4'), (5, 'In 5')], default=1),
        ),
    ]
