# Generated by Django 3.0.6 on 2020-06-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0026_auto_20200605_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='initiative_cost',
            field=models.SmallIntegerField(default=3),
        ),
    ]
