# Generated by Django 3.0.6 on 2020-05-25 20:47

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0027_auto_20200525_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadmember',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.Session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='squadmember',
            name='flight_group',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='session', chained_model_field='session', on_delete=django.db.models.deletion.CASCADE, related_name='squad_members', to='campaign.FlightGroup'),
        ),
    ]
