# Generated by Django 3.2.4 on 2021-06-13 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0027_auto_20210613_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fgsetup',
            name='flight_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_members', to='campaign.flightgroup'),
        ),
    ]
