# Generated by Django 3.0.6 on 2020-06-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0027_campaign_initiative_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='initiative_sq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_init',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='campaign',
            name='upgrade_logic',
            field=models.IntegerField(choices=[(1, 'HotAC')], default=1),
            preserve_default=False,
        ),
    ]
