# Generated by Django 3.0.6 on 2020-05-25 21:06

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0028_auto_20200525_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightgroup',
            name='session',
        ),
        migrations.RemoveField(
            model_name='squadmember',
            name='session',
        ),
        migrations.AddField(
            model_name='flightgroup',
            name='mission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.Mission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squadmember',
            name='mission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.Mission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='squadmember',
            name='flight_group',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='mission', chained_model_field='mission', on_delete=django.db.models.deletion.CASCADE, related_name='squad_members', to='campaign.FlightGroup'),
        ),
    ]
