# Generated by Django 3.0.6 on 2020-06-07 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0011_upgrade_force'),
        ('campaign', '0028_auto_20200607_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotUpgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copies', models.PositiveSmallIntegerField(default=1)),
                ('lost', models.BooleanField(default=False)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Pilot')),
                ('upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwtools.Upgrade')),
            ],
        ),
        migrations.RemoveField(
            model_name='pilot',
            name='upgrades',
        ),
        migrations.AddField(
            model_name='pilot',
            name='upgrades',
            field=models.ManyToManyField(through='campaign.PilotUpgrade', to='xwtools.Upgrade'),
        ),
    ]
