# Generated by Django 3.2.4 on 2021-06-14 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0028_alter_fgsetup_flight_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='deck_draw',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='rulebook',
            name='starter_mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starts', to='campaign.mission'),
        ),
    ]
