# Generated by Django 3.2.4 on 2021-06-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0029_auto_20210614_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['story', 'sequence']},
        ),
        migrations.AddField(
            model_name='mission',
            name='enemy_vp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mission',
            name='player_vp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flightgroup',
            name='orders',
            field=models.CharField(choices=[('A', 'Attack'), ('S', 'Strike'), ('E', 'Escort'), ('X', 'Special')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='mission',
            name='territory',
            field=models.CharField(choices=[('F', 'Friendly'), ('N', 'Neutral'), ('H', 'Hostile')], default='N', max_length=1),
        ),
    ]
