# Generated by Django 3.0.6 on 2020-05-25 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0029_auto_20200525_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squadmember',
            old_name='int',
            new_name='init',
        ),
    ]
