# Generated by Django 3.0.6 on 2020-05-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0030_auto_20200525_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightgroup',
            name='orders',
            field=models.CharField(choices=[('A', 'Attack'), ('S', 'Strike'), ('E', 'Escort'), ('X', 'Special')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='squadmember',
            name='action',
            field=models.CharField(choices=[('A', 'Add'), ('R', 'Replace')], default='A', max_length=1),
        ),
    ]
