# Generated by Django 3.2.4 on 2021-06-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0030_auto_20210618_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='victory',
            field=models.PositiveSmallIntegerField(default=12),
        ),
    ]
