# Generated by Django 3.0.6 on 2020-05-25 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0031_auto_20200525_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightgroup',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_groups', to='campaign.Mission'),
        ),
    ]
