# Generated by Django 3.2.4 on 2021-06-23 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0004_auto_20210613_1255'),
        ('campaign', '0031_alter_campaign_victory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ally',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('init', models.PositiveSmallIntegerField(default=1)),
                ('abilities', models.ManyToManyField(limit_choices_to={'ai_description__isnull': False}, to='xwtools.Upgrade')),
                ('chassis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwtools.chassis')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.mission')),
            ],
        ),
    ]
