# Generated by Django 3.2.4 on 2021-06-23 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0034_alter_ally_mission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ally',
            old_name='name',
            new_name='callsign',
        ),
    ]
