# Generated by Django 3.2.4 on 2021-06-23 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0035_rename_name_ally_callsign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fgsetup',
            name='mission',
        ),
    ]
