# Generated by Django 3.2.4 on 2021-06-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0005_auto_20210624_1211'),
        ('campaign', '0036_remove_fgsetup_mission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ally',
            options={'verbose_name_plural': 'Allies'},
        ),
        migrations.AlterModelOptions(
            name='fgsetup',
            options={'verbose_name': 'Squad Member', 'verbose_name_plural': 'Squad Members'},
        ),
        migrations.AlterModelOptions(
            name='flightgroup',
            options={'verbose_name': 'Flight Group', 'verbose_name_plural': 'Flight Groups'},
        ),
        migrations.AlterField(
            model_name='ally',
            name='abilities',
            field=models.ManyToManyField(blank=True, limit_choices_to={'ai_description__isnull': False}, null=True, to='xwtools.Upgrade'),
        ),
        migrations.AlterField(
            model_name='enemypilot',
            name='name_override',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='flightgroup',
            name='vector',
            field=models.CharField(max_length=6),
        ),
    ]
