# Generated by Django 3.2.4 on 2021-06-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0006_auto_20210624_1251'),
        ('campaign', '0037_auto_20210624_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ally',
            name='abilities',
            field=models.ManyToManyField(blank=True, limit_choices_to={'ai_description__isnull': False}, to='xwtools.Upgrade'),
        ),
    ]
