# Generated by Django 3.2.4 on 2021-06-26 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0009_auto_20210626_1447'),
        ('campaign', '0039_remove_pilotupgrade_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulebook',
            name='faction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xwtools.faction'),
        ),
        migrations.AlterField(
            model_name='rulebook',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
