# Generated by Django 3.2.4 on 2021-06-30 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0017_pilotcard2'),
        ('campaign', '0040_auto_20210626_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotupgrade',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xwtools.card'),
        ),
        migrations.AlterField(
            model_name='pilotupgrade',
            name='upgrade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.campaignupgrade'),
        ),
    ]
