# Generated by Django 3.2.4 on 2021-06-30 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0018_auto_20210630_0014'),
        ('campaign', '0041_auto_20210630_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemyability',
            name='card',
            field=models.ForeignKey(default=1, limit_choices_to={'ai_description__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='xwtools.card'),
            preserve_default=False,
        ),
    ]
