# Generated by Django 3.2.4 on 2021-06-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0019_rename_pilotcard_oldpilotcard'),
        ('campaign', '0042_enemyability_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemyability',
            name='upgrade',
        ),
        migrations.AlterField(
            model_name='enemypilot',
            name='upgrades',
            field=models.ManyToManyField(through='campaign.EnemyAbility', to='xwtools.Card'),
        ),
    ]
