# Generated by Django 3.2.4 on 2021-06-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0019_rename_pilotcard_oldpilotcard'),
        ('campaign', '0043_auto_20210630_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pilotupgrade',
            options={'ordering': ['card__type', 'status']},
        ),
        migrations.RemoveField(
            model_name='pilotupgrade',
            name='upgrade',
        ),
        migrations.AlterField(
            model_name='ally',
            name='abilities',
            field=models.ManyToManyField(blank=True, limit_choices_to={'ai_description__isnull': False}, to='xwtools.Card'),
        ),
        migrations.DeleteModel(
            name='CampaignUpgrade',
        ),
    ]
