# Generated by Django 3.2.4 on 2021-07-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0044_auto_20210630_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotship',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
