# Generated by Django 3.2.4 on 2021-07-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0045_pilotship_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotship',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
