# Generated by Django 3.2.4 on 2021-07-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0046_pilotship_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fgsetup',
            index=models.Index(fields=['players'], name='campaign_fg_players_1e9636_idx'),
        ),
        migrations.AddIndex(
            model_name='fgsetup',
            index=models.Index(fields=['init'], name='campaign_fg_init_e0ba35_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['story', 'sequence'], name='campaign_mi_story_16a802_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['rulebook'], name='campaign_mi_ruleboo_76e770_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['player_vp'], name='campaign_mi_player__753ba4_idx'),
        ),
    ]
