# Generated by Django 3.2.4 on 2021-07-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0047_auto_20210704_0324'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pilotship',
            index=models.Index(fields=['active'], name='campaign_pi_active_14aaf2_idx'),
        ),
    ]
