# Generated by Django 3.2.4 on 2021-07-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0048_pilotship_campaign_pi_active_14aaf2_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ai',
            name='version',
        ),
        migrations.AlterField(
            model_name='aipriority',
            name='type',
            field=models.CharField(choices=[('U', 'System Phase'), ('T', 'Target'), ('A', 'Action')], max_length=1),
        ),
    ]
