# Generated by Django 3.2.4 on 2021-07-06 16:33

import campaign.models.campaigns
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0033_alter_card_options'),
        ('campaign', '0050_campaign_exclude_random'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='exclude_random',
            field=models.ManyToManyField(to='xwtools.Chassis'),
        ),
    ]
