# Generated by Django 3.2.4 on 2021-07-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0052_mission_ground_assault'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='bonus_xp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
