# Generated by Django 3.2.4 on 2021-07-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0053_pilot_bonus_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotupgrade',
            name='cost',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
