# Generated by Django 3.2.4 on 2021-07-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0054_pilotupgrade_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulebook',
            name='initiative_sq',
            field=models.PositiveSmallIntegerField(choices=[(1, 'HotAC')]),
        ),
    ]
