# Generated by Django 3.2.4 on 2021-07-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0055_alter_rulebook_initiative_sq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulebook',
            old_name='initiative_sq',
            new_name='initiative_progression',
        ),
        migrations.AlterField(
            model_name='rulebook',
            name='initiative_cost',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='rulebook',
            name='ship_cost',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='rulebook',
            name='start_init',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='rulebook',
            name='upgrade_logic',
            field=models.PositiveSmallIntegerField(choices=[(1, 'HotAC')]),
        ),
    ]
