# Generated by Django 3.2.4 on 2021-07-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0038_alter_dialmaneuver_bearing'),
        ('campaign', '0056_auto_20210709_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='exclude_random',
            field=models.ManyToManyField(blank=True, to='xwtools.Chassis'),
        ),
        migrations.AlterField(
            model_name='rulebook',
            name='initiative_progression',
            field=models.PositiveSmallIntegerField(choices=[(1, 'HotAC'), (2, 'Test')]),
        ),
        migrations.AlterField(
            model_name='rulebook',
            name='upgrade_logic',
            field=models.PositiveSmallIntegerField(choices=[(1, 'HotAC'), (2, 'Test')]),
        ),
    ]
