# Generated by Django 3.2.4 on 2021-07-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0057_auto_20210711_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('attack', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hull', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shields', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='features',
            field=models.ManyToManyField(blank=True, to='campaign.MissionFeatures'),
        ),
    ]
