# Generated by Django 3.2.4 on 2021-07-11 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0058_auto_20210711_2221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MissionFeatures',
            new_name='MissionFeature',
        ),
    ]
