# Generated by Django 3.2.4 on 2021-07-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0059_rename_missionfeatures_missionfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionfeature',
            name='setup_code',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='missionfeature',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
