# Generated by Django 3.2.4 on 2021-07-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0060_auto_20210711_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionfeature',
            name='attack_range',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
