# Generated by Django 3.2.4 on 2021-07-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0061_missionfeature_attack_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionfeature',
            name='agility',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
