# Generated by Django 3.2.4 on 2021-07-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0062_missionfeature_agility'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionfeature',
            name='type',
            field=models.CharField(choices=[('E', 'Emplacement'), ('O', 'Obstacle'), ('T', 'Terrain')], default='E', max_length=1),
            preserve_default=False,
        ),
    ]
