# Generated by Django 3.2.4 on 2021-07-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0063_missionfeature_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimaneuver',
            name='arc',
            field=models.CharField(choices=[('BE', 'Bullseye'), ('FR', 'Front (Right)'), ('RF', 'Right (Front)'), ('RA', 'Right (Rear)'), ('AR', 'Rear (Right)'), ('FL', 'Front (Left)'), ('LF', 'Left (Front)'), ('LA', 'Left (Rear)'), ('AL', 'Rear (Left)'), ('SP', 'Special')], max_length=2),
        ),
        migrations.AlterField(
            model_name='aimaneuver',
            name='range',
            field=models.CharField(choices=[('1', 'R1/R2 Closing'), ('2', 'R3/R2 Fleeing'), ('3', 'R4+'), ('4', 'Stressed'), ('5', 'Hyperspace'), ('6', 'Decloak')], max_length=1),
        ),
    ]
