# Generated by Django 3.2.4 on 2021-07-12 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0064_auto_20210712_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='fgsetup',
            name='enemy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.enemypilot'),
        ),
    ]
