# Generated by Django 3.0.6 on 2020-06-10 20:21

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chassis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=20, null=True)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('H', 'Huge')], default='S', max_length=1)),
                ('attack', models.PositiveSmallIntegerField(default=0)),
                ('attack_arc', models.CharField(choices=[('F', 'Front'), ('R', 'Rear')], default='F', max_length=2)),
                ('attack2', models.PositiveSmallIntegerField(default=0)),
                ('attack2_arc', models.CharField(blank=True, choices=[('F', 'Front'), ('R', 'Rear')], max_length=2, null=True)),
                ('agility', models.PositiveSmallIntegerField(default=0)),
                ('hull', models.PositiveSmallIntegerField(default=0)),
                ('shields', models.PositiveSmallIntegerField(default=0)),
                ('hyperdrive', models.BooleanField(default=True)),
                ('cloaking', models.BooleanField(default=False)),
                ('css', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'verbose_name_plural': 'Chassis',
            },
        ),
        migrations.CreateModel(
            name='Dial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('default_ship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_for', to='xwtools.Chassis')),
                ('ships', models.ManyToManyField(to='xwtools.Chassis')),
            ],
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_description', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('TLN', 'Talent'), ('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Config'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('PLT', 'Pilot'), ('GNR', 'Gunner'), ('ILC', 'Illicit`'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TCH', 'Tech'), ('TRP', 'Torpedo'), ('TTL', 'Title'), ('TRT', 'Turret'), ('SHP', 'Ship')], max_length=3)),
                ('type2', models.CharField(blank=True, choices=[('TLN', 'Talent'), ('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Config'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('PLT', 'Pilot'), ('GNR', 'Gunner'), ('ILC', 'Illicit`'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TCH', 'Tech'), ('TRP', 'Torpedo'), ('TTL', 'Title'), ('TRT', 'Turret'), ('SHP', 'Ship')], default=None, max_length=3, null=True)),
                ('charges', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('force', models.BooleanField(default=False)),
                ('cost', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['type', '-type2', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TLN', 'Talent'), ('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Config'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('PLT', 'Pilot'), ('GNR', 'Gunner'), ('ILC', 'Illicit`'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TCH', 'Tech'), ('TRP', 'Torpedo'), ('TTL', 'Title'), ('TRT', 'Turret'), ('SHP', 'Ship')], max_length=3)),
                ('initiative', models.PositiveSmallIntegerField(default=1)),
                ('chassis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='xwtools.Chassis')),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_description', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('TLN', 'Talent'), ('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Config'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('PLT', 'Pilot'), ('GNR', 'Gunner'), ('ILC', 'Illicit`'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TCH', 'Tech'), ('TRP', 'Torpedo'), ('TTL', 'Title'), ('TRT', 'Turret'), ('SHP', 'Ship')], max_length=3)),
                ('type2', models.CharField(blank=True, choices=[('TLN', 'Talent'), ('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Config'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('PLT', 'Pilot'), ('GNR', 'Gunner'), ('ILC', 'Illicit`'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TCH', 'Tech'), ('TRP', 'Torpedo'), ('TTL', 'Title'), ('TRT', 'Turret'), ('SHP', 'Ship')], default=None, max_length=3, null=True)),
                ('charges', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('force', models.BooleanField(default=False)),
                ('initiative', models.PositiveSmallIntegerField(default=1)),
                ('chassis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwtools.Chassis')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwtools.Faction')),
            ],
            options={
                'ordering': ['type', '-type2', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DialManeuver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.PositiveSmallIntegerField()),
                ('bearing', models.CharField(choices=[('S', 'Straight'), ('B', 'Bank'), ('T', 'Turn'), ('KT', 'K-Turn'), ('TR', 'Tallon Roll'), ('SL', 'Sloop'), ('RB', 'Reverse Bank'), ('SS', 'Stationary'), ('XX', '--')], max_length=3)),
                ('direction', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=1, null=True)),
                ('difficulty', models.CharField(choices=[('B', 'Blue'), ('W', 'White'), ('R', 'Red'), ('P', 'Purple')], default='W', max_length=1)),
                ('dial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maneuvers', to='xwtools.Dial')),
            ],
            options={
                'ordering': ['-speed', django.db.models.expressions.CombinedExpression(django.db.models.expressions.Case(django.db.models.expressions.When(bearing='XX', then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(bearing='S', then=django.db.models.expressions.Value(2)), django.db.models.expressions.When(bearing='B', then=django.db.models.expressions.Value(3)), django.db.models.expressions.When(bearing='T', then=django.db.models.expressions.Value(4)), django.db.models.expressions.When(bearing='TR', then=django.db.models.expressions.Value(5)), django.db.models.expressions.When(bearing='SL', then=django.db.models.expressions.Value(6)), django.db.models.expressions.When(bearing='KT', then=django.db.models.expressions.Value(8)), output_field=models.SmallIntegerField()), '*', django.db.models.expressions.Case(django.db.models.expressions.When(direction='L', then=django.db.models.expressions.Value(-1)), default=django.db.models.expressions.Value(1), output_field=models.SmallIntegerField()))],
            },
        ),
        migrations.AddField(
            model_name='chassis',
            name='ability',
            field=models.OneToOneField(blank=True, limit_choices_to={'type': 'SHP'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xwtools.Upgrade'),
        ),
        migrations.AddField(
            model_name='chassis',
            name='dial',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chassis', to='xwtools.Dial'),
        ),
    ]
