# Generated by Django 3.0.6 on 2020-05-25 23:18

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    replaces = [('xwtools', '0001_initial'), ('xwtools', '0002_auto_20200520_0224'), ('xwtools', '0003_auto_20200520_1153'), ('xwtools', '0004_auto_20200520_1827'), ('xwtools', '0005_auto_20200520_1831'), ('xwtools', '0006_auto_20200520_1842'), ('xwtools', '0007_auto_20200520_2019'), ('xwtools', '0008_auto_20200521_1253'), ('xwtools', '0009_auto_20200521_2010'), ('xwtools', '0010_auto_20200522_0108'), ('xwtools', '0011_auto_20200522_2018'), ('xwtools', '0012_chassis_attack'), ('xwtools', '0013_auto_20200522_2136'), ('xwtools', '0014_dial_hyperdrive'), ('xwtools', '0015_chassis_cloaking'), ('xwtools', '0016_auto_20200523_2146'), ('xwtools', '0017_auto_20200523_2153'), ('xwtools', '0018_dial_name'), ('xwtools', '0019_chassis_css'), ('xwtools', '0020_auto_20200525_2216')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('hyperdrive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chassis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=20, null=True)),
                ('agility', models.PositiveSmallIntegerField(default=0)),
                ('attack2', models.PositiveSmallIntegerField(default=0)),
                ('attack2_arc', models.CharField(blank=True, choices=[('F', 'Front'), ('R', 'Rear')], max_length=2, null=True)),
                ('attack_arc', models.CharField(choices=[('F', 'Front'), ('R', 'Rear')], default='F', max_length=2)),
                ('hull', models.PositiveSmallIntegerField(default=0)),
                ('shields', models.PositiveSmallIntegerField(default=0)),
                ('attack', models.PositiveSmallIntegerField(default=0)),
                ('cloaking', models.BooleanField(default=False)),
                ('hyperdrive', models.BooleanField(default=True)),
                ('css', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Configuration'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('GNR', 'Gunner'), ('ILC', 'Illicit'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TLN', 'Talent'), ('TCH', 'Tech'), ('TTL', 'Title'), ('TRP', 'Torpedo'), ('TRT', 'Turret'), ('SHP', 'Ship'), ('PLT', 'Pilot'), ('THR', 'Initiative'), ('FCH', 'Force Charge'), ('CHR', 'Charge'), ('WLD', 'Wildcard')], max_length=3)),
                ('type2', models.CharField(blank=True, choices=[('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Configuration'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('GNR', 'Gunner'), ('ILC', 'Illicit'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TLN', 'Talent'), ('TCH', 'Tech'), ('TTL', 'Title'), ('TRP', 'Torpedo'), ('TRT', 'Turret'), ('SHP', 'Ship'), ('PLT', 'Pilot'), ('THR', 'Initiative'), ('FCH', 'Force Charge'), ('CHR', 'Charge'), ('WLD', 'Wildcard')], default=None, max_length=3, null=True)),
                ('cost', models.PositiveSmallIntegerField()),
                ('charges', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['type', '-type2', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DialManeuver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.PositiveSmallIntegerField()),
                ('bearing', models.CharField(choices=[('S', 'Straight'), ('B', 'Bank'), ('T', 'Turn'), ('KT', 'K-Turn'), ('TR', 'Tallon Roll'), ('SL', 'Sloop'), ('RB', 'Reverse Bank'), ('SS', 'Stationary'), ('XX', '--')], max_length=3)),
                ('direction', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=1, null=True)),
                ('difficulty', models.CharField(choices=[('B', 'Blue'), ('W', 'White'), ('R', 'Red'), ('P', 'Purple')], default='W', max_length=1)),
                ('dial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maneuvers', to='xwtools.Dial')),
            ],
            options={
                'ordering': ['-speed', django.db.models.expressions.CombinedExpression(django.db.models.expressions.Case(django.db.models.expressions.When(bearing='XX', then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(bearing='S', then=django.db.models.expressions.Value(2)), django.db.models.expressions.When(bearing='B', then=django.db.models.expressions.Value(3)), django.db.models.expressions.When(bearing='T', then=django.db.models.expressions.Value(4)), django.db.models.expressions.When(bearing='TR', then=django.db.models.expressions.Value(5)), django.db.models.expressions.When(bearing='SL', then=django.db.models.expressions.Value(6)), django.db.models.expressions.When(bearing='KT', then=django.db.models.expressions.Value(8)), output_field=models.SmallIntegerField()), '*', django.db.models.expressions.Case(django.db.models.expressions.When(direction='L', then=django.db.models.expressions.Value(-1)), default=django.db.models.expressions.Value(1), output_field=models.SmallIntegerField()))],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'Talent'), ('1', 'Astromech'), ('2', 'Cannon'), ('3', 'Config'), ('4', 'Crew'), ('5', 'Device'), ('6', 'Pilot'), ('7', 'Gunner'), ('8', 'Illicit'), ('9', 'Missile'), ('10', 'Modification'), ('11', 'Sensor'), ('12', 'Relay'), ('13', 'Tech'), ('14', 'Title'), ('15', 'Torpedo'), ('16', 'Turret')], max_length=3)),
                ('chassis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='xwtools.Chassis')),
                #('chassis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='xwtools.Ship')),
                ('initiative', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='dial',
            name='chassis',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='xwtools.Chassis'),
        ),
        migrations.RemoveField(
            model_name='dial',
            name='hyperdrive',
        ),
        migrations.AddField(
            model_name='dial',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('default_ship', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='default_for', to='xwtools.Chassis')),
                ('ships', models.ManyToManyField(to='xwtools.Chassis')),
            ],
        ),
    ]
