# Generated by Django 3.2 on 2022-07-03 20:39

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('ai_description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('TLN', 'Talent'), ('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Config'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('PLT', 'Pilot'), ('GNR', 'Gunner'), ('ILC', 'Illicit'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TCH', 'Tech'), ('TRP', 'Torpedo'), ('TTL', 'Title'), ('TRT', 'Turret'), ('SHP', 'Ship'), ('COM', 'Command'), ('HRD', 'Hardpoint'), ('CRG', 'Cargo'), ('TEM', 'Team')], max_length=3)),
                ('type2', models.CharField(blank=True, choices=[('TLN', 'Talent'), ('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Config'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('PLT', 'Pilot'), ('GNR', 'Gunner'), ('ILC', 'Illicit'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TCH', 'Tech'), ('TRP', 'Torpedo'), ('TTL', 'Title'), ('TRT', 'Turret'), ('SHP', 'Ship'), ('COM', 'Command'), ('HRD', 'Hardpoint'), ('CRG', 'Cargo'), ('TEM', 'Team')], default=None, max_length=3, null=True)),
                ('charges', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recurring', models.BooleanField(default=False)),
                ('force', models.BooleanField(default=False)),
                ('cost', models.SmallIntegerField(default=0)),
                ('repeat', models.BooleanField(default=False)),
                ('initiative', models.PositiveSmallIntegerField(default=1, null=True)),
                ('adds', models.CharField(blank=True, max_length=120, null=True)),
                ('requires', models.CharField(blank=True, max_length=120, null=True)),
                ('limited', models.SmallIntegerField(choices=[(0, ''), (1, '•'), (2, '••'), (3, '•••')], default=0)),
                ('player_use', models.BooleanField(default=True)),
                ('ai_use', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Chassis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(blank=True, max_length=40, null=True)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('H', 'Huge')], default='S', max_length=1)),
                ('attack', models.PositiveSmallIntegerField(default=0)),
                ('attack_arc', models.CharField(choices=[('F', 'Front Arc'), ('R', 'Rear Arc'), ('T', 'Single Turret Arc'), ('TT', 'Double Turret Arc'), ('FF', 'Full Front Arc'), ('RR', 'Full Rear Arc'), ('B', 'Bullseye Arc'), ('SL', 'Left Arc'), ('SR', 'Right Arc')], default='F', max_length=2)),
                ('attack2', models.PositiveSmallIntegerField(default=0)),
                ('attack2_arc', models.CharField(blank=True, choices=[('F', 'Front Arc'), ('R', 'Rear Arc'), ('T', 'Single Turret Arc'), ('TT', 'Double Turret Arc'), ('FF', 'Full Front Arc'), ('RR', 'Full Rear Arc'), ('B', 'Bullseye Arc'), ('SL', 'Left Arc'), ('SR', 'Right Arc')], max_length=2, null=True)),
                ('agility', models.PositiveSmallIntegerField(default=0)),
                ('hull', models.PositiveSmallIntegerField(default=0)),
                ('shields', models.PositiveSmallIntegerField(default=0)),
                ('energy', models.PositiveSmallIntegerField(default=0)),
                ('hyperdrive', models.BooleanField(default=True)),
                ('walker', models.BooleanField(default=False)),
                ('armor', models.PositiveSmallIntegerField(default=0)),
                ('css', models.CharField(blank=True, max_length=80, null=True)),
                ('ability', models.ForeignKey(blank=True, limit_choices_to={'type': 'SHP'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ship', to='xwtools.card')),
            ],
            options={
                'verbose_name_plural': 'Chassis',
            },
        ),
        migrations.CreateModel(
            name='Dial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dial', to='xwtools.chassis')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TLN', 'Talent'), ('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Config'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('PLT', 'Pilot'), ('GNR', 'Gunner'), ('ILC', 'Illicit'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TCH', 'Tech'), ('TRP', 'Torpedo'), ('TTL', 'Title'), ('TRT', 'Turret'), ('SHP', 'Ship'), ('COM', 'Command'), ('HRD', 'Hardpoint'), ('CRG', 'Cargo'), ('TEM', 'Team')], max_length=3)),
                ('initiative', models.PositiveSmallIntegerField(default=1)),
                ('chassis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='xwtools.chassis')),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('default_ship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_for', to='xwtools.chassis')),
                ('ships', models.ManyToManyField(to='xwtools.Chassis')),
            ],
        ),
        migrations.CreateModel(
            name='DialManeuver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.SmallIntegerField()),
                ('bearing', models.CharField(choices=[('S', 'Straight'), ('B', 'Bank'), ('T', 'Turn'), ('KT', 'K-Turn'), ('TR', 'Tallon Roll'), ('SL', 'Sloop'), ('RB', 'Reverse Bank'), ('SS', 'Stationary'), ('RS', 'Reverse Straight'), ('XX', '--')], max_length=3)),
                ('direction', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=1, null=True)),
                ('difficulty', models.CharField(choices=[('B', 'Blue'), ('W', 'White'), ('R', 'Red'), ('P', 'Purple')], default='W', max_length=1)),
                ('dial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maneuvers', to='xwtools.dial')),
            ],
            options={
                'ordering': ['-speed', django.db.models.expressions.CombinedExpression(django.db.models.expressions.Case(django.db.models.expressions.When(bearing='XX', then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(bearing='S', then=django.db.models.expressions.Value(2)), django.db.models.expressions.When(bearing='RS', then=django.db.models.expressions.Value(2)), django.db.models.expressions.When(bearing='SS', then=django.db.models.expressions.Value(2)), django.db.models.expressions.When(bearing='B', then=django.db.models.expressions.Value(3)), django.db.models.expressions.When(bearing='RB', then=django.db.models.expressions.Value(3)), django.db.models.expressions.When(bearing='T', then=django.db.models.expressions.Value(4)), django.db.models.expressions.When(bearing='TR', then=django.db.models.expressions.Value(5)), django.db.models.expressions.When(bearing='SL', then=django.db.models.expressions.Value(6)), django.db.models.expressions.When(bearing='KT', then=django.db.models.expressions.Value(8)), output_field=models.SmallIntegerField()), '*', django.db.models.expressions.Case(django.db.models.expressions.When(direction='L', then=django.db.models.expressions.Value(-1)), default=django.db.models.expressions.Value(1), output_field=models.SmallIntegerField()))],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='chassis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xwtools.chassis'),
        ),
        migrations.AddField(
            model_name='card',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xwtools.faction'),
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arc', models.CharField(choices=[('F', 'Front Arc'), ('R', 'Rear Arc'), ('T', 'Single Turret Arc'), ('TT', 'Double Turret Arc'), ('FF', 'Full Front Arc'), ('RR', 'Full Rear Arc'), ('B', 'Bullseye Arc'), ('SL', 'Left Arc'), ('SR', 'Right Arc')], default='F', max_length=2)),
                ('dice', models.PositiveSmallIntegerField(default=3)),
                ('range', models.CharField(max_length=3)),
                ('ordnance', models.BooleanField(default=False)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xwtools.card')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BRO', 'Barrel Roll'), ('BST', 'Boost'), ('CLT', 'Calculate'), ('CLK', 'Cloak'), ('CRD', 'Coordinate'), ('EVD', 'Evade'), ('FCS', 'Focus'), ('LCK', 'Lock'), ('JAM', 'Jam'), ('RLD', 'Reload'), ('RNF', 'Reinforce'), ('RTT', 'Rotate Arc'), ('SLM', 'SLAM')], max_length=3)),
                ('difficulty', models.CharField(choices=[('B', 'Blue'), ('W', 'White'), ('R', 'Red'), ('P', 'Purple')], default='W', max_length=1)),
                ('linked_action', models.CharField(blank=True, choices=[('BRO', 'Barrel Roll'), ('BST', 'Boost'), ('CLT', 'Calculate'), ('CLK', 'Cloak'), ('CRD', 'Coordinate'), ('EVD', 'Evade'), ('FCS', 'Focus'), ('LCK', 'Lock'), ('JAM', 'Jam'), ('RLD', 'Reload'), ('RNF', 'Reinforce'), ('RTT', 'Rotate Arc'), ('SLM', 'SLAM')], max_length=3)),
                ('linked_difficulty', models.CharField(blank=True, choices=[('B', 'Blue'), ('W', 'White'), ('R', 'Red'), ('P', 'Purple')], max_length=1)),
                ('chassis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='xwtools.chassis')),
            ],
        ),
        migrations.CreateModel(
            name='PilotCard',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('xwtools.card',),
        ),
        migrations.CreateModel(
            name='ShipAbility',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Ship Abilities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('xwtools.card',),
        ),
        migrations.CreateModel(
            name='UpgradeCard',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('xwtools.card',),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['type'], name='xwtools_car_type_acc167_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['force'], name='xwtools_car_force_20f287_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['initiative'], name='xwtools_car_initiat_dea412_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['chassis'], name='xwtools_car_chassis_42559c_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['faction'], name='xwtools_car_faction_51edbe_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['player_use'], name='xwtools_car_player__0a6d08_idx'),
        ),
    ]
