# Generated by Django 3.0.6 on 2020-05-26 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0001_squashed_0020_auto_20200525_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='default_ship',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_for', to='xwtools.Chassis'),
        ),
    ]
