# Generated by Django 3.0.6 on 2020-06-10 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='chassis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_card', to='xwtools.Chassis'),
        ),
    ]
