# Generated by Django 3.0.6 on 2020-05-20 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='playable',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='start_xp',
        ),
    ]
