# Generated by Django 3.2.4 on 2021-06-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0002_auto_20200610_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='attack2_arc',
            field=models.CharField(blank=True, choices=[('F', 'Front'), ('R', 'Rear'), ('T', 'Turret'), ('TT', 'Double Turret'), ('FF', 'Full Front'), ('RR', 'Full Rear'), ('B', 'Bullseye')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='chassis',
            name='attack_arc',
            field=models.CharField(choices=[('F', 'Front'), ('R', 'Rear'), ('T', 'Turret'), ('TT', 'Double Turret'), ('FF', 'Full Front'), ('RR', 'Full Rear'), ('B', 'Bullseye')], default='F', max_length=2),
        ),
    ]
