# Generated by Django 3.0.6 on 2020-05-20 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0003_auto_20200520_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='threat',
        ),
        migrations.AddField(
            model_name='slot',
            name='initiative',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='slot',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='xwtools.Ship'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='type',
            field=models.CharField(choices=[(1, 'astromech'), (2, 'cannon'), (3, 'config'), (4, 'crew'), (5, 'device'), (6, 'pilot'), (7, 'gunner'), (8, 'illicit'), (9, 'missile'), (10, 'mod'), (11, 'sensor'), (12, 'relay'), (13, 'tech'), (14, 'title'), (15, 'torpedo'), (16, 'turret')], max_length=3),
        ),
        migrations.DeleteModel(
            name='TreeSlot',
        ),
    ]
