# Generated by Django 3.2.4 on 2021-06-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0003_auto_20210610_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='ai_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='ai_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
