# Generated by Django 3.0.6 on 2020-05-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0004_auto_20200520_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='type',
            field=models.CharField(choices=[(1, 'Astromech'), (2, 'Cannon'), (3, 'Config'), (4, 'Crew'), (5, 'Device'), (6, 'Pilot'), (7, 'Gunner'), (8, 'Illicit'), (9, 'Missile'), (10, 'Mod'), (11, 'Sensor'), (12, 'Relay'), (13, 'Tech'), (14, 'Title'), (15, 'Torpedo'), (16, 'Turret')], max_length=3),
        ),
    ]
