# Generated by Django 3.2.4 on 2021-06-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0004_auto_20210613_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='chassis',
            name='energy',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chassis',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='type',
            field=models.CharField(choices=[('TLN', 'Talent'), ('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Config'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('PLT', 'Pilot'), ('GNR', 'Gunner'), ('ILC', 'Illicit'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TCH', 'Tech'), ('TRP', 'Torpedo'), ('TTL', 'Title'), ('TRT', 'Turret'), ('SHP', 'Ship'), ('COM', 'Command'), ('HRD', 'Hardpoint'), ('CRG', 'Cargo'), ('TEM', 'Team')], max_length=3),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='type2',
            field=models.CharField(blank=True, choices=[('TLN', 'Talent'), ('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Config'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('PLT', 'Pilot'), ('GNR', 'Gunner'), ('ILC', 'Illicit'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TCH', 'Tech'), ('TRP', 'Torpedo'), ('TTL', 'Title'), ('TRT', 'Turret'), ('SHP', 'Ship'), ('COM', 'Command'), ('HRD', 'Hardpoint'), ('CRG', 'Cargo'), ('TEM', 'Team')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='type',
            field=models.CharField(choices=[('TLN', 'Talent'), ('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Config'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('PLT', 'Pilot'), ('GNR', 'Gunner'), ('ILC', 'Illicit'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TCH', 'Tech'), ('TRP', 'Torpedo'), ('TTL', 'Title'), ('TRT', 'Turret'), ('SHP', 'Ship'), ('COM', 'Command'), ('HRD', 'Hardpoint'), ('CRG', 'Cargo'), ('TEM', 'Team')], max_length=3),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='type',
            field=models.CharField(choices=[('TLN', 'Talent'), ('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Config'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('PLT', 'Pilot'), ('GNR', 'Gunner'), ('ILC', 'Illicit'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TCH', 'Tech'), ('TRP', 'Torpedo'), ('TTL', 'Title'), ('TRT', 'Turret'), ('SHP', 'Ship'), ('COM', 'Command'), ('HRD', 'Hardpoint'), ('CRG', 'Cargo'), ('TEM', 'Team')], max_length=3),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='type2',
            field=models.CharField(blank=True, choices=[('TLN', 'Talent'), ('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Config'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('PLT', 'Pilot'), ('GNR', 'Gunner'), ('ILC', 'Illicit'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TCH', 'Tech'), ('TRP', 'Torpedo'), ('TTL', 'Title'), ('TRT', 'Turret'), ('SHP', 'Ship'), ('COM', 'Command'), ('HRD', 'Hardpoint'), ('CRG', 'Cargo'), ('TEM', 'Team')], default=None, max_length=3, null=True),
        ),
    ]
