# Generated by Django 3.0.6 on 2020-05-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0005_auto_20200527_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='ai_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
