# Generated by Django 3.0.6 on 2020-05-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0006_auto_20200520_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialmaneuver',
            old_name='color',
            new_name='difficulty'
        ),
    ]
