# Generated by Django 3.2.4 on 2021-06-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0006_auto_20210624_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dial',
            name='name',
        ),
    ]
