# Generated by Django 3.0.6 on 2020-05-29 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0006_auto_20200528_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dial',
            name='chassis',
        ),
        migrations.AddField(
            model_name='chassis',
            name='dial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chassis', to='xwtools.Dial'),
        ),
    ]
