# Generated by Django 3.2.4 on 2021-06-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0007_remove_dial_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
    ]
