# Generated by Django 3.0.6 on 2020-05-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0007_auto_20200520_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialmaneuver',
            name='difficulty',
            field=models.CharField(choices=[('B', 'Blue'), ('W', 'White'), ('R', 'Red'), ('P', 'Purple')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='slot',
            name='type',
            field=models.CharField(choices=[('1', 'Astromech'), ('2', 'Cannon'), ('3', 'Config'), ('4', 'Crew'), ('5', 'Device'), ('6', 'Pilot'), ('7', 'Gunner'), ('8', 'Illicit'), ('9', 'Missile'), ('10', 'Modification'), ('11', 'Sensor'), ('12', 'Relay'), ('13', 'Tech'), ('14', 'Title'), ('15', 'Torpedo'), ('16', 'Turret')], max_length=3),
        ),
    ]
