# Generated by Django 3.0.6 on 2020-05-29 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0007_auto_20200529_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='dial',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chassis', to='xwtools.Dial'),
        ),
    ]
