# Generated by Django 3.0.6 on 2020-05-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0008_auto_20200529_0241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chassis',
            options={'verbose_name_plural': 'Chassis'},
        ),
    ]
