# Generated by Django 3.2.4 on 2021-06-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0009_auto_20210626_1447'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pilot',
            new_name='PilotCard',
        ),
    ]
