# Generated by Django 3.0.6 on 2020-05-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0009_auto_20200529_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='chassis',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('H', 'Huge')], default='S', max_length=1),
        ),
    ]
