# Generated by Django 3.0.6 on 2020-05-22 01:08

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        #('campaign', '0012_auto_20200522_0108'),
        ('xwtools', '0009_auto_20200521_2010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ship',
            new_name='Chassis',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='ship',
            new_name='chassis',
        ),
    ]
