# Generated by Django 3.0.6 on 2020-05-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0010_auto_20200522_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='chassis',
            name='agility',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chassis',
            name='attack2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chassis',
            name='attack2_arc',
            field=models.CharField(choices=[('F', 'Front'), ('R', 'Rear')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='chassis',
            name='attack_arc',
            field=models.CharField(choices=[('F', 'Front'), ('R', 'Rear')], default='F', max_length=2),
        ),
        migrations.AddField(
            model_name='chassis',
            name='hull',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chassis',
            name='shields',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
