# Generated by Django 3.2.4 on 2021-06-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0010_rename_pilot_pilotcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='attack2_arc',
            field=models.CharField(blank=True, choices=[('F', 'Front'), ('R', 'Rear'), ('T', 'Turret'), ('TT', 'Double Turret'), ('FF', 'Full Front'), ('RR', 'Full Rear'), ('B', 'Bullseye'), ('SL', 'Left'), ('SR', 'Right')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='chassis',
            name='attack_arc',
            field=models.CharField(choices=[('F', 'Front'), ('R', 'Rear'), ('T', 'Turret'), ('TT', 'Double Turret'), ('FF', 'Full Front'), ('RR', 'Full Rear'), ('B', 'Bullseye'), ('SL', 'Left'), ('SR', 'Right')], default='F', max_length=2),
        ),
    ]
