# Generated by Django 3.0.6 on 2020-06-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0010_chassis_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='force',
            field=models.BooleanField(default=False),
        ),
    ]
