# Generated by Django 3.2.4 on 2021-06-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0011_auto_20210629_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='adds',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='attack_arc',
            field=models.CharField(blank=True, choices=[('F', 'Front'), ('R', 'Rear'), ('T', 'Turret'), ('TT', 'Double Turret'), ('FF', 'Full Front'), ('RR', 'Full Rear'), ('B', 'Bullseye'), ('SL', 'Left'), ('SR', 'Right')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='attack_dice',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='attack_ordnance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='attack_range',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='attack_requires',
            field=models.CharField(blank=True, choices=[('L', 'Lock'), ('F', 'Focus'), ('C', 'Calculate'), ('J', 'Force')], max_length=1, null=True),
        ),
    ]
