# Generated by Django 3.2.4 on 2021-06-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0012_auto_20210629_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrade',
            name='attack_dice',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
