# Generated by Django 3.0.6 on 2020-05-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0012_chassis_attack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='attack2_arc',
            field=models.CharField(blank=True, choices=[('F', 'Front'), ('R', 'Rear')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='type',
            field=models.CharField(choices=[('0', 'Talent'), ('1', 'Astromech'), ('2', 'Cannon'), ('3', 'Config'), ('4', 'Crew'), ('5', 'Device'), ('6', 'Pilot'), ('7', 'Gunner'), ('8', 'Illicit'), ('9', 'Missile'), ('10', 'Modification'), ('11', 'Sensor'), ('12', 'Relay'), ('13', 'Tech'), ('14', 'Title'), ('15', 'Torpedo'), ('16', 'Turret')], max_length=3),
        ),
    ]
