# Generated by Django 3.2.4 on 2021-06-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0013_alter_upgrade_attack_dice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires', models.CharField(blank=True, choices=[('L', 'Lock'), ('F', 'Focus'), ('C', 'Calculate'), ('J', 'Force')], max_length=1, null=True)),
                ('arc', models.CharField(choices=[('F', 'Front'), ('R', 'Rear'), ('T', 'Turret'), ('TT', 'Double Turret'), ('FF', 'Full Front'), ('RR', 'Full Rear'), ('B', 'Bullseye'), ('SL', 'Left'), ('SR', 'Right')], default='F', max_length=2)),
                ('dice', models.PositiveSmallIntegerField(default=3)),
                ('range', models.CharField(max_length=3)),
                ('ordnance', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='upgrade',
            name='attack_arc',
        ),
        migrations.RemoveField(
            model_name='upgrade',
            name='attack_dice',
        ),
        migrations.RemoveField(
            model_name='upgrade',
            name='attack_ordnance',
        ),
        migrations.RemoveField(
            model_name='upgrade',
            name='attack_range',
        ),
        migrations.RemoveField(
            model_name='upgrade',
            name='attack_requires',
        ),
    ]
