# Generated by Django 3.0.6 on 2020-05-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0014_dial_hyperdrive'),
    ]

    operations = [
        migrations.AddField(
            model_name='chassis',
            name='cloaking',
            field=models.BooleanField(default=False),
        ),
    ]
