# Generated by Django 3.2.4 on 2021-06-29 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0014_auto_20210629_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('ai_description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('TLN', 'Talent'), ('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Config'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('PLT', 'Pilot'), ('GNR', 'Gunner'), ('ILC', 'Illicit'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TCH', 'Tech'), ('TRP', 'Torpedo'), ('TTL', 'Title'), ('TRT', 'Turret'), ('SHP', 'Ship'), ('COM', 'Command'), ('HRD', 'Hardpoint'), ('CRG', 'Cargo'), ('TEM', 'Team')], max_length=3)),
                ('type2', models.CharField(blank=True, choices=[('TLN', 'Talent'), ('AST', 'Astromech'), ('CNN', 'Cannon'), ('CNF', 'Config'), ('CRW', 'Crew'), ('DVC', 'Device'), ('FRC', 'Force Power'), ('PLT', 'Pilot'), ('GNR', 'Gunner'), ('ILC', 'Illicit'), ('MSL', 'Missile'), ('MOD', 'Modification'), ('SNS', 'Sensor'), ('TAC', 'Tactical Relay'), ('TCH', 'Tech'), ('TRP', 'Torpedo'), ('TTL', 'Title'), ('TRT', 'Turret'), ('SHP', 'Ship'), ('COM', 'Command'), ('HRD', 'Hardpoint'), ('CRG', 'Cargo'), ('TEM', 'Team')], default=None, max_length=3, null=True)),
                ('charges', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recurring', models.BooleanField(default=False)),
                ('force', models.BooleanField(default=False)),
                ('cost', models.SmallIntegerField(default=0)),
                ('repeat', models.BooleanField(default=False)),
                ('adds', models.CharField(blank=True, max_length=120, null=True)),
                ('initiative', models.PositiveSmallIntegerField(default=1)),
                ('chassis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwtools.chassis')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwtools.faction')),
            ],
        ),
    ]
