# Generated by Django 3.2.4 on 2021-06-30 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0015_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeCard',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('xwtools.card',),
        ),
    ]
