# Generated by Django 3.0.6 on 2020-05-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0017_auto_20200523_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='dial',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
