# Generated by Django 3.2.4 on 2021-06-30 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0017_pilotcard2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='chassis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xwtools.chassis'),
        ),
        migrations.AlterField(
            model_name='card',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xwtools.faction'),
        ),
        migrations.AlterField(
            model_name='card',
            name='initiative',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
    ]
