# Generated by Django 3.2.4 on 2021-06-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0018_auto_20210630_0014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PilotCard',
            new_name='OldPilotCard',
        ),
    ]
