# Generated by Django 3.0.6 on 2020-05-25 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0019_chassis_css'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chassis',
            name='faction',
        ),
        migrations.AddField(
            model_name='faction',
            name='default_ship',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='default_for', to='xwtools.Chassis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faction',
            name='ships',
            field=models.ManyToManyField(to='xwtools.Chassis'),
        ),
    ]
