# Generated by Django 3.2.4 on 2021-06-30 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0019_rename_pilotcard_oldpilotcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='attack',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xwtools.attack'),
        ),
    ]
