# Generated by Django 3.2.4 on 2021-06-30 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0020_card_attack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='attack',
        ),
        migrations.AddField(
            model_name='attack',
            name='card',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='xwtools.card'),
            preserve_default=False,
        ),
    ]
