# Generated by Django 3.2.4 on 2021-07-01 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0022_auto_20210701_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='new_ability',
            field=models.OneToOneField(blank=True, limit_choices_to={'type': 'SHP'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_ship', to='xwtools.card'),
        ),
    ]
