# Generated by Django 3.2.4 on 2021-07-01 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0023_alter_chassis_new_ability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chassis',
            name='ability',
        ),
    ]
