# Generated by Django 3.2.4 on 2021-07-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0025_auto_20210701_0237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipability',
            options={'verbose_name_plural': 'Ship Abilities'},
        ),
        migrations.AddField(
            model_name='card',
            name='requires',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
