# Generated by Django 3.2.4 on 2021-07-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0026_auto_20210701_1229'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['type'], name='xwtools_car_type_acc167_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['force'], name='xwtools_car_force_20f287_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['initiative'], name='xwtools_car_initiat_dea412_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['chassis'], name='xwtools_car_chassis_42559c_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['faction'], name='xwtools_car_faction_51edbe_idx'),
        ),
    ]
