# Generated by Django 3.2.4 on 2021-07-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0027_auto_20210704_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='ai_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='player_use',
            field=models.BooleanField(default=True),
        ),
    ]
