# Generated by Django 3.2.4 on 2021-07-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0028_auto_20210704_0251'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['player_use'], name='xwtools_car_player__0a6d08_idx'),
        ),
    ]
