# Generated by Django 3.2.4 on 2021-07-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0029_card_xwtools_car_player__0a6d08_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldpilotcard',
            name='chassis',
        ),
        migrations.RemoveField(
            model_name='oldpilotcard',
            name='faction',
        ),
        migrations.DeleteModel(
            name='Upgrade',
        ),
        migrations.DeleteModel(
            name='OldPilotCard',
        ),
    ]
