# Generated by Django 3.2.4 on 2021-07-04 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0030_auto_20210704_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BRO', 'Barrel Roll'), ('BST', 'Boost'), ('CLT', 'Calculate'), ('CLK', 'Cloak'), ('CRD', 'Coordinate'), ('EVD', 'Evade'), ('FCS', 'Focus'), ('LCK', 'Lock'), ('JAM', 'Jam'), ('RLD', 'Reload'), ('RNF', 'Reinforce'), ('RTT', 'Rotate ARC'), ('SLM', 'SLAM')], max_length=3)),
                ('difficulty', models.CharField(choices=[('B', 'Blue'), ('W', 'White'), ('R', 'Red'), ('P', 'Purple')], default='W', max_length=1)),
                ('linked_action', models.CharField(blank=True, choices=[('BRO', 'Barrel Roll'), ('BST', 'Boost'), ('CLT', 'Calculate'), ('CLK', 'Cloak'), ('CRD', 'Coordinate'), ('EVD', 'Evade'), ('FCS', 'Focus'), ('LCK', 'Lock'), ('JAM', 'Jam'), ('RLD', 'Reload'), ('RNF', 'Reinforce'), ('RTT', 'Rotate ARC'), ('SLM', 'SLAM')], max_length=3)),
                ('linked_difficulty', models.CharField(blank=True, choices=[('B', 'Blue'), ('W', 'White'), ('R', 'Red'), ('P', 'Purple')], default='R', max_length=1)),
                ('chassis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwtools.chassis')),
            ],
        ),
    ]
