# Generated by Django 3.2.4 on 2021-07-04 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0031_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.CharField(choices=[('BRO', 'Barrel Roll'), ('BST', 'Boost'), ('CLT', 'Calculate'), ('CLK', 'Cloak'), ('CRD', 'Coordinate'), ('EVD', 'Evade'), ('FCS', 'Focus'), ('LCK', 'Lock'), ('JAM', 'Jam'), ('RLD', 'Reload'), ('RNF', 'Reinforce'), ('RTT', 'Rotate Arc'), ('SLM', 'SLAM')], max_length=3),
        ),
        migrations.AlterField(
            model_name='action',
            name='chassis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='xwtools.chassis'),
        ),
        migrations.AlterField(
            model_name='action',
            name='linked_action',
            field=models.CharField(blank=True, choices=[('BRO', 'Barrel Roll'), ('BST', 'Boost'), ('CLT', 'Calculate'), ('CLK', 'Cloak'), ('CRD', 'Coordinate'), ('EVD', 'Evade'), ('FCS', 'Focus'), ('LCK', 'Lock'), ('JAM', 'Jam'), ('RLD', 'Reload'), ('RNF', 'Reinforce'), ('RTT', 'Rotate Arc'), ('SLM', 'SLAM')], max_length=3),
        ),
        migrations.AlterField(
            model_name='action',
            name='linked_difficulty',
            field=models.CharField(blank=True, choices=[('B', 'Blue'), ('W', 'White'), ('R', 'Red'), ('P', 'Purple')], max_length=1),
        ),
    ]
