# Generated by Django 3.2.4 on 2021-07-05 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0032_auto_20210704_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['type', 'name']},
        ),
    ]
