# Generated by Django 3.2.4 on 2021-07-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0033_alter_card_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chassis',
            name='cloaking',
        ),
        migrations.AddField(
            model_name='chassis',
            name='armor',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chassis',
            name='walker',
            field=models.BooleanField(default=False),
        ),
    ]
