# Generated by Django 3.2.4 on 2021-07-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0037_alter_dialmaneuver_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialmaneuver',
            name='bearing',
            field=models.CharField(choices=[('S', 'Straight'), ('B', 'Bank'), ('T', 'Turn'), ('KT', 'K-Turn'), ('TR', 'Tallon Roll'), ('SL', 'Sloop'), ('RB', 'Reverse Bank'), ('SS', 'Stationary'), ('RS', 'Reverse Straight'), ('XX', '--')], max_length=3),
        ),
    ]
