# Generated by Django 3.2.4 on 2021-07-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwtools', '0038_alter_dialmaneuver_bearing'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='limited',
            field=models.SmallIntegerField(choices=[(0, ''), (1, '•'), (2, '••'), (3, '•••')], default=0),
        ),
    ]
